import { registerUsersServiceFixture } from './users.service.users-service.test-fixture';
import { registerShouldBeDefinedCases } from './users.service.users-service.email-changes.behaviors.test-cases';
import { registerFindOneCases } from './users.service.users-service.email-changes.behaviors.test-cases';
import { registerRollbackFailedRegistrationCases } from './users.service.users-service.email-changes.behaviors.test-cases';
import { registerCreateOneCases } from './users.service.users-service.build-username-from-ssoclaim.behaviors.test-cases';
import { registerBuildUsernameFromSsoclaimCases } from './users.service.users-service.build-username-from-ssoclaim.behaviors.test-cases';
import { registerUpdateUserCases } from './users.service.users-service.email-changes.behaviors.test-cases';
import { registerFindManyCases } from './users.service.findmany.should-require-users-with-an-sso-provider.behaviors.test-cases';
import { registerChangeUsernameCases } from './users.service.users-service.change-username.test-cases';
import { registerCreateOneLocaleCases } from './users.service.users-service.build-username-from-ssoclaim.behaviors.test-cases';
import { registerUpdateLocaleCases } from './users.service.users-service.email-changes.behaviors.test-cases';
import { registerConfirmSelfDeletionCases } from './users.service.users-service.confirm-self-deletion.test-cases';
import { registerEmailChangesCases } from './users.service.users-service.email-changes.behaviors.test-cases';
import { registerBulkUserRoleAssignmentCases } from './users.service.users-service.build-username-from-ssoclaim.behaviors.test-cases';
describe('UsersService', () => {
  const fixture = registerUsersServiceFixture();
  registerShouldBeDefinedCases(fixture);
  registerFindOneCases(fixture);
  registerRollbackFailedRegistrationCases(fixture);
  registerCreateOneCases(fixture);
  registerBuildUsernameFromSsoclaimCases(fixture);
  registerUpdateUserCases(fixture);
  registerFindManyCases(fixture);
  registerChangeUsernameCases(fixture);
  registerCreateOneLocaleCases(fixture);
  registerUpdateLocaleCases(fixture);
  registerConfirmSelfDeletionCases(fixture);
  registerEmailChangesCases(fixture);
  registerBulkUserRoleAssignmentCases(fixture);
});
