import { registerResourceRetrainingServiceEvaluateFixture } from './resourceRetraining.service.resource-retraining-service-evaluate.test-fixture';
import { registerDoesNotApplyWhenNoThresholdsAreConfiguredCases } from './resourceRetraining.service.resource-retraining-service-evaluate.becomes-due-once-the-max-training-age-has-passed.behaviors.test-cases';
import { registerBecomesDueOnceTheMaxTrainingAgeHasPassedCases } from './resourceRetraining.service.resource-retraining-service-evaluate.becomes-due-once-the-max-training-age-has-passed.behaviors.test-cases';
import { registerUsesLastUsageAsTheInactivityBaselineCases } from './resourceRetraining.service.resource-retraining-service-evaluate.retries-failed-email-delivery-without-marking-the-notification-delivered.behaviors.test-cases';
import { registerFallsBackToTrainedAtForInactivityWhenThereIsNoUsageCases } from './resourceRetraining.service.resource-retraining-service-evaluate.becomes-due-once-the-max-training-age-has-passed.behaviors.test-cases';
import { registerReportsTheSoonestTriggerWhenBothAreConfiguredCases } from './resourceRetraining.service.resource-retraining-service-evaluate.becomes-due-once-the-max-training-age-has-passed.behaviors.test-cases';
import { registerPassesThroughTheBlocksAccessFlagCases } from './resourceRetraining.service.resource-retraining-service-evaluate.becomes-due-once-the-max-training-age-has-passed.behaviors.test-cases';
import { registerRecordsASystemOriginRequiredTransitionWhenTheScheduledEvaluationFirstNotifCases } from './resourceRetraining.service.resource-retraining-service-evaluate.becomes-due-once-the-max-training-age-has-passed.behaviors.test-cases';
import { registerRetriesFailedEmailDeliveryWithoutMarkingTheNotificationDeliveredCases } from './resourceRetraining.service.resource-retraining-service-evaluate.retries-failed-email-delivery-without-marking-the-notification-delivered.behaviors.test-cases';
import { registerRetriesAMissingRequiredEventAfterTheEmailHasBeenDeliveredCases } from './resourceRetraining.service.resource-retraining-service-evaluate.becomes-due-once-the-max-training-age-has-passed.behaviors.test-cases';
import { registerDoesNotRecordRetrainingForARevokedIntroductionCases } from './resourceRetraining.service.resource-retraining-service-evaluate.becomes-due-once-the-max-training-age-has-passed.behaviors.test-cases';
import { registerUsesTheIntroductionMarkerAfterAuditRetentionHasRemovedTheAuditRowCases } from './resourceRetraining.service.resource-retraining-service-evaluate.retries-failed-email-delivery-without-marking-the-notification-delivered.behaviors.test-cases';
import { registerResourceRetrainingServiceStatusAggregationFixture } from './resourceRetraining.service.resource-retraining-service-status-aggregation.test-fixture';
import { registerCombinesExpiredResourceAndGroupIntroductionsIntoABlockedStatusCases } from './resourceRetraining.service.resource-retraining-service-status-aggregation.combines-expired-resource-and-group-introductions-into-a-blocked-status.behaviors.test-cases';
import { registerKeepsAFreshGroupIntroductionUsableWhenTheResourceIntroductionIsExpiredCases } from './resourceRetraining.service.resource-retraining-service-status-aggregation.combines-expired-resource-and-group-introductions-into-a-blocked-status.behaviors.test-cases';
import { registerReportsNoApplicablePolicyWithoutIncorrectlyDroppingAnExistingIntroductionCases } from './resourceRetraining.service.resource-retraining-service-status-aggregation.combines-expired-resource-and-group-introductions-into-a-blocked-status.behaviors.test-cases';
import { registerReportsMissingOrRevokedIntroductionsAsUnavailableCases } from './resourceRetraining.service.resource-retraining-service-status-aggregation.combines-expired-resource-and-group-introductions-into-a-blocked-status.behaviors.test-cases';
import { registerEvaluatesIndividualResourceAndGroupIntroductionsAndToleratesDeletedTargetsCases } from './resourceRetraining.service.resource-retraining-service-status-aggregation.combines-expired-resource-and-group-introductions-into-a-blocked-status.behaviors.test-cases';
describe('ResourceRetrainingService.evaluate', () => {
  const fixture = registerResourceRetrainingServiceEvaluateFixture();
  registerDoesNotApplyWhenNoThresholdsAreConfiguredCases(fixture);
  registerBecomesDueOnceTheMaxTrainingAgeHasPassedCases(fixture);
  registerUsesLastUsageAsTheInactivityBaselineCases(fixture);
  registerFallsBackToTrainedAtForInactivityWhenThereIsNoUsageCases(fixture);
  registerReportsTheSoonestTriggerWhenBothAreConfiguredCases(fixture);
  registerPassesThroughTheBlocksAccessFlagCases(fixture);
  registerRecordsASystemOriginRequiredTransitionWhenTheScheduledEvaluationFirstNotifCases(fixture);
  registerRetriesFailedEmailDeliveryWithoutMarkingTheNotificationDeliveredCases(fixture);
  registerRetriesAMissingRequiredEventAfterTheEmailHasBeenDeliveredCases(fixture);
  registerDoesNotRecordRetrainingForARevokedIntroductionCases(fixture);
  registerUsesTheIntroductionMarkerAfterAuditRetentionHasRemovedTheAuditRowCases(fixture);
});
describe('ResourceRetrainingService status aggregation', () => {
  const fixture = registerResourceRetrainingServiceStatusAggregationFixture();
  registerCombinesExpiredResourceAndGroupIntroductionsIntoABlockedStatusCases(fixture);
  registerKeepsAFreshGroupIntroductionUsableWhenTheResourceIntroductionIsExpiredCases(fixture);
  registerReportsNoApplicablePolicyWithoutIncorrectlyDroppingAnExistingIntroductionCases(fixture);
  registerReportsMissingOrRevokedIntroductionsAsUnavailableCases(fixture);
  registerEvaluatesIndividualResourceAndGroupIntroductionsAndToleratesDeletedTargetsCases(fixture);
});
