import { useUserManagementPageState } from './useUserManagementPageState';
export type Props = Pick<
  ReturnType<typeof useUserManagementPageState>,
  | 't'
  | 'activeFilters'
  | 'replaceFilter'
  | 'roleExcludes'
  | 'roleMatch'
  | 'setRoleCondition'
  | 'roles'
  | 'roleName'
  | 'excludeRoleIds'
  | 'roleIds'
  | 'updateFilters'
  | 'emailVerified'
  | 'ssoProviderExcludes'
  | 'ssoProviderMatch'
  | 'setSsoProviderCondition'
  | 'ssoProviders'
  | 'ssoProviderNone'
  | 'hasSsoProvider'
  | 'excludeSsoProviderIds'
  | 'ssoProviderIds'
  | 'removeFilter'
  | 'addFilter'
>;
