import { registerRbacServiceFixture } from './rbac.service.rbac-service.test-fixture';
import { registerDetectsTheLastActiveAdministratorAndHandlesAbsentRoleAssignmentsCases } from './rbac.service.rbac-service.assign-default-roles.behaviors.test-cases';
import { registerAssignsARoleByKeyIdempotentlyAndSupportsAContainingTransactionCases } from './rbac.service.rbac-service.assign-default-roles.behaviors.test-cases';
import { registerShouldBeDefinedCases } from './rbac.service.rbac-service.get-effective-permissions.behaviors.test-cases';
import { registerLooksUpASingleRoleKeyWithoutLoadingRolePermissionsCases } from './rbac.service.rbac-service.get-effective-permissions.behaviors.test-cases';
import { registerGetEffectivePermissionsCases } from './rbac.service.rbac-service.get-effective-permissions.behaviors.test-cases';
import { registerGetUserIdsWithPermissionCases } from './rbac.service.rbac-service.get-effective-permissions.behaviors.test-cases';
import { registerAssignRoleCases } from './rbac.service.rbac-service.assign-default-roles.behaviors.test-cases';
import { registerRevokeRoleCases } from './rbac.service.rbac-service.revoke-role.test-cases';
import { registerSyncSsoRolesCases } from './rbac.service.rbac-service.sync-sso-roles.test-cases';
import { registerAssignDefaultRolesCases } from './rbac.service.rbac-service.assign-default-roles.behaviors.test-cases';
import { registerGetRolesWithUsageCases } from './rbac.service.rbac-service.get-effective-permissions.behaviors.test-cases';
import { registerCreateRoleCases } from './rbac.service.rbac-service.assign-default-roles.behaviors.test-cases';
import { registerUpdateRoleCases } from './rbac.service.rbac-service.update-role.test-cases';
import { registerDeleteRoleCases } from './rbac.service.rbac-service.delete-role.test-cases';
describe('RbacService', () => {
  const fixture = registerRbacServiceFixture();
  registerDetectsTheLastActiveAdministratorAndHandlesAbsentRoleAssignmentsCases(fixture);
  registerAssignsARoleByKeyIdempotentlyAndSupportsAContainingTransactionCases(fixture);
  registerShouldBeDefinedCases(fixture);
  registerLooksUpASingleRoleKeyWithoutLoadingRolePermissionsCases(fixture);
  registerGetEffectivePermissionsCases(fixture);
  registerGetUserIdsWithPermissionCases(fixture);
  registerAssignRoleCases(fixture);
  registerRevokeRoleCases(fixture);
  registerSyncSsoRolesCases(fixture);
  registerAssignDefaultRolesCases(fixture);
  registerGetRolesWithUsageCases(fixture);
  registerCreateRoleCases(fixture);
  registerUpdateRoleCases(fixture);
  registerDeleteRoleCases(fixture);
});
