version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      nx:
        patterns:
          - 'nx'
          - '@nx/*'
      nestjs:
        patterns:
          - '@nestjs/*'
          - '@nestjs-modules/*'
      typescript-eslint:
        patterns:
          - 'typescript-eslint'
          - '@typescript-eslint/*'
      testing:
        patterns:
          - 'jest'
          - '@jest/*'
          - 'jest-*'
          - 'ts-jest'
          - 'babel-jest'
          - 'vitest'
          - '@vitest/*'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      swc:
        patterns:
          - '@swc/*'
      babel:
        patterns:
          - '@babel/*'
          - 'babel-*'
