ARG NODE_VERSION=24.13.0
ARG NODE_VERSION_NAME=trixie

FROM node:${NODE_VERSION}-${NODE_VERSION_NAME}

ARG APP_UID=10001
ARG APP_GID=10001

RUN groupadd -g ${APP_GID} appuser && useradd -u ${APP_UID} -g ${APP_GID} -m -d /app -s /usr/sbin/nologin appuser

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends libstdc++6 gosu && rm -rf /var/lib/apt/lists/*

COPY dist dist
COPY docs docs
COPY deploy/api /app/dist/apps/api
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENV STATIC_FRONTEND_FILE_PATH=/app/dist/apps/frontend
ENV STATIC_DOCS_FILE_PATH=/app/docs

RUN mkdir -p /app/storage/plugins
ENV STORAGE_ROOT=/app/storage
ENV PLUGIN_DIR=/app/storage/plugins

EXPOSE 3000

ENTRYPOINT ["/entrypoint.sh"]
CMD ["node", "dist/apps/api/main.js"]
