import { registerAuthControllerFixture } from './auth.controller.auth-controller.test-fixture';
import { registerShouldBeDefinedCases } from './auth.controller.auth-controller.does-not-record-a-successful-logout-when-passport-reports-a-callback-error.behaviors.test-cases';
import { registerShouldCreateASessionForProgrammaticClientCases } from './auth.controller.auth-controller.does-not-record-a-successful-logout-when-passport-reports-a-callback-error.behaviors.test-cases';
import { registerShouldCreateASessionForWebBrowserAndSetCookieCases } from './auth.controller.auth-controller.does-not-record-a-successful-logout-when-passport-reports-a-callback-error.behaviors.test-cases';
import { registerUsesPassportLogoutWithItsRequestReceiverAndAwaitsTheAuditReceiptCases } from './auth.controller.auth-controller.uses-passport-logout-with-its-request-receiver-and-awaits-the-audit-receipt.test-cases';
import { registerShouldDeleteASessionWithCookieTokenCases } from './auth.controller.auth-controller.does-not-record-a-successful-logout-when-passport-reports-a-callback-error.behaviors.test-cases';
import { registerDoesNotRecordASuccessfulLogoutWhenPassportReportsACallbackErrorCases } from './auth.controller.auth-controller.does-not-record-a-successful-logout-when-passport-reports-a-callback-error.behaviors.test-cases';
import { registerShouldRefreshSessionForProgrammaticClientCases } from './auth.controller.auth-controller.does-not-record-a-successful-logout-when-passport-reports-a-callback-error.behaviors.test-cases';
import { registerShouldRefreshSessionForWebBrowserAndUpdateCookieCases } from './auth.controller.auth-controller.does-not-record-a-successful-logout-when-passport-reports-a-callback-error.behaviors.test-cases';
describe('AuthController', () => {
  const fixture = registerAuthControllerFixture();
  registerShouldBeDefinedCases(fixture);
  registerShouldCreateASessionForProgrammaticClientCases(fixture);
  registerShouldCreateASessionForWebBrowserAndSetCookieCases(fixture);
  registerUsesPassportLogoutWithItsRequestReceiverAndAwaitsTheAuditReceiptCases(fixture);
  registerShouldDeleteASessionWithCookieTokenCases(fixture);
  registerDoesNotRecordASuccessfulLogoutWhenPassportReportsACallbackErrorCases(fixture);
  registerShouldRefreshSessionForProgrammaticClientCases(fixture);
  registerShouldRefreshSessionForWebBrowserAndUpdateCookieCases(fixture);
});
