import { registerAuthServiceFixture } from './auth.service.auth-service.test-fixture';
import { registerStoresLocalPasswordHashesAndSsoSubjectsInTheSelectedTransactionCases } from './auth.service.auth-service.stores-local-password-hashes-and-sso-subjects-in-the-selected-transaction.test-cases';
import { registerConsumesValidCurrentAndLegacyEmailVerificationTokensSCases } from './auth.service.auth-service.consumes-valid-current-and-legacy-email-verification-tokens-s.test-cases';
import { registerRejectsMissingUsersInvalidTokensAndExpiredVerificationLinksWithoutModifyingCases } from './auth.service.auth-service.rejects-missing-users-invalid-tokens-and-expired-verification-links-without-modifying.test-cases';
import { registerShouldBeDefinedCases } from './auth.service.auth-service.should-be-defined.test-cases';
import { registerShouldAuthenticateUserWithCorrectCredentialsCases } from './auth.service.auth-service.should-authenticate-user-with-correct-credentials.test-cases';
import { registerShouldNotAuthenticateUserWithIncorrectCredentialsCases } from './auth.service.auth-service.should-not-authenticate-user-with-incorrect-credentials.test-cases';
import { registerShouldNotAuthenticateANonExistentUserCases } from './auth.service.auth-service.should-not-authenticate-a-non-existent-user.test-cases';
import { registerFindSsoauthenticationDetailCases } from './auth.service.auth-service.find-ssoauthentication-detail.test-cases';
import { registerUpdateSsosubjectCases } from './auth.service.auth-service.update-ssosubject.test-cases';
import { registerUserHasSsoauthenticationCases } from './auth.service.auth-service.user-has-ssoauthentication.test-cases';
describe('AuthService', () => {
  const fixture = registerAuthServiceFixture();
  registerStoresLocalPasswordHashesAndSsoSubjectsInTheSelectedTransactionCases(fixture);
  registerConsumesValidCurrentAndLegacyEmailVerificationTokensSCases(fixture);
  registerRejectsMissingUsersInvalidTokensAndExpiredVerificationLinksWithoutModifyingCases(fixture);
  registerShouldBeDefinedCases(fixture);
  registerShouldAuthenticateUserWithCorrectCredentialsCases(fixture);
  registerShouldNotAuthenticateUserWithIncorrectCredentialsCases(fixture);
  registerShouldNotAuthenticateANonExistentUserCases(fixture);
  registerFindSsoauthenticationDetailCases(fixture);
  registerUpdateSsosubjectCases(fixture);
  registerUserHasSsoauthenticationCases(fixture);
});
