version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: attraccess
      POSTGRES_PASSWORD: attraccess
      POSTGRES_DB: attraccess
    ports:
      - '2345:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - '8025:8025'
      - '1025:1025'

volumes:
  postgres_data:
