services:
  mailpit:
    image: axllent/mailpit:latest
    ports:
      - '8025:8025'
      - '1025:1025'
  
  mqtt:
    image: eclipse-mosquitto:2.0
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - ./config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data/mosquitto:/mosquitto/data
      - ./log/mosquitto:/mosquitto/log

  mqtt-explorer:
    image: emqx/mqttx-web
    ports:
      - '4000:80'
    depends_on:
      - mqtt

