version: '2.4'

services:
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
      - '1900:1900'
    volumes:
      - proxy-data:/data
      - proxy-letsencrypt:/etc/letsencrypt
    environment:
      - INITIAL_ADMIN_EMAIL=admin@attraccess.org
      - INITIAL_ADMIN_PASSWORD=password

  attraccess:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - attraccess-storage:/app/storage
    env_file:
      - .env.local

  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped

  webhook-site:
    image: tarampampam/webhook-tester:latest
    restart: unless-stopped
    environment:
      - STORAGE_DRIVER=fs
      - FS_STORAGE_DIR=/storage
    volumes:
      - webhook-site:/storage

  bunkerm: #BunkerM is an MQTT Broker
    image: bunkeriot/bunkerm:latest
    restart: unless-stopped
    #environment:
    #  - HOST_ADDRESS=mqtt.attraccess.demo
    #  - FRONTEND_URL=http://mqtt.attraccess.demo
    #  - ALLOWED_ORIGINS=http://mqtt.attraccess.demo
    volumes:
      - bunkerm_mosquitto_data:/var/lib/mosquitto
      - bunkerm_mosquitto_conf:/etc/mosquitto
      - bunkerm_auth_data:/data

  zigbee2mqtt:
    image: ghcr.io/koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - zigbee2mqtt:/app/data
    #environment:
    #  - TZ=Europe/Amsterdam

volumes:
  attraccess-storage:
  bunkerm_mosquitto_data:
  bunkerm_mosquitto_conf:
  bunkerm_auth_data:
  webhook-site:
  zigbee2mqtt:
  proxy-data:
  proxy-letsencrypt:
