name: 'attraccess'

services:
  attraccess:
    restart: unless-stopped
    image: attraccess/attraccess:${ATTRACCESS_TAG:-nightly-latest}
    ports:
      - '80:3000'
    COMMENT_ENV: 'Please take care of backing up the env file'
    env_file:
      - ./.env.example.docker-compose
    COMMENT_VOLUMES: 'Please take care of backing up the storage directory'
    volumes:
      - ./storage/attraccess:/app/storage
    depends_on:
      - bunkerm

  bunkerm:
    comment: 'BunkerM is an MQTT Broker'
    image: bunkeriot/bunkerm:latest
    restart: unless-stopped
    ports:
      - '1883:1883' # MQTT broker port
      - '9001:9001' # WebSocket port (if needed)
      - '2000:2000' # Web UI
      - '1900:1900' # Internal admin API
    environment:
      - HOST_ADDRESS=mqtt.attraccess.demo
      - FRONTEND_URL=http://mqtt.attraccess.demo
      - ALLOWED_ORIGINS=http://mqtt.attraccess.demo
    volumes:
      - bunkerm_mosquitto_data:/var/lib/mosquitto
      - bunkerm_mosquitto_conf:/etc/mosquitto
      - bunkerm_auth_data:/data
