import { EmailTemplateType } from '@attraccess/database-entities';
export const emailResourceDefaults = {
  [EmailTemplateType.RESOURCE_USAGE_BILLING_TRANSACTION_SUMMARY]: {
    subject: '{{t "subject" "Your usage receipt for {resource}" resource=resource.name}}',
    variables: [
      'user.username',
      'user.email',
      'host.frontend',
      'host.backend',
      'resource.id',
      'resource.name',
      'usage.startTime',
      'usage.endTime',
      'usage.roundedMinutes',
      'usage.billingFactor',
      'items[].name',
      'items[].description',
      'items[].quantity',
      'items[].isUnavailable',
      'items[].unitPrice',
      'items[].total',
      'items[].isFixedFee',
      'items[].isSessionDuration',
      'items[].isOperatingDuration',
      'items[].isBillingFactor',
      'items[].isDuration',
      'items[].durationMs',
      'items[].hasDuration',
      'items[].durationSeconds',
      'totalCredits',
      'newBalance',
    ],
  },

  [EmailTemplateType.RESOURCE_HEALTH_CHANGED]: {
    subject:
      '{{#if health.isDegraded}}{{t "subject_degraded" "Resource degraded: {resource}" resource=resource.name}}{{else}}{{t "subject_recovered" "Resource recovered: {resource}" resource=resource.name}}{{/if}}',
    variables: [
      'user.username',
      'user.email',
      'user.id',
      'host.frontend',
      'host.backend',
      'resource.id',
      'resource.name',
      'resource.url',
      'health.status',
      'health.previousStatus',
      'health.reason',
      'health.identifier',
      'health.isDegraded',
      'health.headerColor',
    ],
  },

  [EmailTemplateType.USER_RETRAINING_REQUIRED]: {
    subject: '{{t "subject" "Retraining required: {resource}" resource=resource.name}}',
    variables: [
      'user.username',
      'user.email',
      'user.id',
      'host.frontend',
      'host.backend',
      'resource.id',
      'resource.name',
      'resource.url',
      'retraining.isAge',
      'retraining.isInactivity',
      'retraining.blocksAccess',
    ],
  },

  [EmailTemplateType.MESSAGE_RECEIVED]: {
    subject: '{{t "subject" "New message from {sender}" sender=message.senderName}}',
    variables: [
      'user.username',
      'user.email',
      'user.id',
      'host.frontend',
      'host.backend',
      'message.senderName',
      'message.preview',
      'message.conversationUrl',
    ],
  },

  [EmailTemplateType.RESOURCE_USAGE_NOTE_ADDED]: {
    subject: '{{t "subject" "New usage note: {resource}" resource=resource.name}}',
    variables: [
      'user.username',
      'user.email',
      'user.id',
      'host.frontend',
      'host.backend',
      'resource.id',
      'resource.name',
      'resource.url',
      'note.authorName',
      'note.content',
      'note.isStart',
    ],
  },

  [EmailTemplateType.RESOURCE_TAKEOVER]: {
    subject: '{{t "subject" "{resource} was taken over" resource=resource.name}}',
    variables: [
      'user.username',
      'user.email',
      'user.id',
      'host.frontend',
      'host.backend',
      'resource.id',
      'resource.name',
      'resource.url',
      'takeover.actorName',
    ],
  },

  [EmailTemplateType.RESOURCE_SESSION_ENDED]: {
    subject: '{{t "subject" "{resource} session ended" resource=resource.name}}',
    variables: [
      'user.username',
      'user.email',
      'user.id',
      'host.frontend',
      'host.backend',
      'resource.id',
      'resource.name',
      'resource.url',
      'session.id',
      'session.endedAt',
      'session.endedBy',
    ],
  },

  [EmailTemplateType.ACCESS_CHANGE]: {
    subject: '{{accessChange.title}}',
    variables: [
      'user.username',
      'user.email',
      'user.id',
      'host.frontend',
      'host.backend',
      'accessChange.title',
      'accessChange.body',
      'accessChange.url',
    ],
  },

  [EmailTemplateType.MAINTENANCE_REQUEST_CREATED]: {
    subject: '{{t "subject" "Maintenance requested: {resource}" resource=resource.name}}',
    variables: [
      'user.username',
      'user.email',
      'user.id',
      'host.frontend',
      'host.backend',
      'resource.id',
      'resource.name',
      'resource.url',
      'request.id',
      'request.reason',
      'request.requestedBy',
    ],
  },
};
