import { registerNpmPluginServiceFixture } from './npm-plugin.service.npm-plugin-service.test-fixture';
import { registerCorrelatesAPersistedInstallWithItsSBootResultWithoutExposingAuditContextCases } from './npm-plugin.service.npm-plugin-service.correlates-a-persisted-install-with-its-s-boot-result-without-exposing-audit-context.test-cases';
import { registerPinsTarballDnsOnEverySameOriginRedirectAndReturnsArchiveBytesCases } from './npm-plugin.service.npm-plugin-service.pins-tarball-dns-on-every-same-origin-redirect-and-returns-archive-bytes.test-cases';
import { registerRejectsTarballRedirectsWithoutDestinationsAcrossOriginsOrBeyondTheLimitCases } from './npm-plugin.service.npm-plugin-service.rejects-tarball-redirects-without-destinations-across-origins-or-beyond-the-limit.test-cases';
import { registerPinsMetadataRequestsToPublicRegistryAddressesAndLimitsTheirSizeCases } from './npm-plugin.service.npm-plugin-service.pins-metadata-requests-to-public-registry-addresses-and-limits-their-size.test-cases';
import { registerReturnsInvalidSearchCandidatesWithAnActionableIncompatibilityReasonCases } from './npm-plugin.service.npm-plugin-service.returns-invalid-search-candidates-with-an-actionable-incompatibility-reason.test-cases';
import { registerHydratesAbbreviatedSearchResultsBeforeValidatingMarketplacePackagesCases } from './npm-plugin.service.npm-plugin-service.hydrates-abbreviated-search-results-before-validating-marketplace-packages.test-cases';
import { registerReturnsAnAttestationUrlWhenTheRegistryProvidesPackageProvenanceCases } from './npm-plugin.service.npm-plugin-service.returns-an-attestation-url-when-the-registry-provides-package-provenance.test-cases';
import { registerDiscoversPluginsThroughRegistryKeywordSearchWithoutAHardcodedPackageListCases } from './npm-plugin.service.npm-plugin-service.discovers-plugins-through-registry-keyword-search-without-a-hardcoded-package-list.test-cases';
import { registerRetainsHydratedMarketplacePackagesWhenAnotherResultNoLongerHasMetadataCases } from './npm-plugin.service.npm-plugin-service.retains-hydrated-marketplace-packages-when-another-result-no-longer-has-metadata.test-cases';
import { registerDoesNotTrustAPackageDeclaredOfficialFlagOrAMismatchedRegistryPublisherCases } from './npm-plugin.service.npm-plugin-service.does-not-trust-a-package-declared-official-flag-or-a-mismatched-registry-publisher.test-cases';
import { registerRejectsMarketplaceMetadataThatClaimsAnAllowlistedPackageIdentityForADifferCases } from './npm-plugin.service.npm-plugin-service.rejects-marketplace-metadata-that-claims-an-allowlisted-package-identity-for-a-differ.test-cases';
import { registerUsesTheSelectedRegistryForDirectMarketplaceLookupCases } from './npm-plugin.service.npm-plugin-service.uses-the-selected-registry-for-direct-marketplace-lookup.test-cases';
import { registerSearchesAConfiguredRegistryWhenItSupportsNpmSearchCases } from './npm-plugin.service.npm-plugin-service.searches-a-configured-registry-when-it-supports-npm-search.test-cases';
import { registerRejectsMetadataRequestsToPrivateRegistryAddressesCases } from './npm-plugin.service.npm-plugin-service.rejects-metadata-requests-to-private-registry-addresses.test-cases';
import { registerDoesNotPersistARegistryWhenTokenStorageFailsCases } from './npm-plugin.service.npm-plugin-service.does-not-persist-a-registry-when-token-storage-fails.test-cases';
import { registerReturnsRegistryMetadataWithoutItsStoredTokenCases } from './npm-plugin.service.npm-plugin-service.returns-registry-metadata-without-its-stored-token.test-cases';
import { registerRejectsRegistryAdditionsBeyondTheConfiguredRegistryLimitCases } from './npm-plugin.service.npm-plugin-service.rejects-registry-additions-beyond-the-configured-registry-limit.test-cases';
import { registerPermitsRetryingRegistryTokenCleanupAfterItsRegistryRecordWasRemovedCases } from './npm-plugin.service.npm-plugin-service.permits-retrying-registry-token-cleanup-after-its-registry-record-was-removed.test-cases';
import { registerPreservesARegistryTokenWhenRemovingItsRecordFailsCases } from './npm-plugin.service.npm-plugin-service.preserves-a-registry-token-when-removing-its-record-fails.test-cases';
import { registerRemovesTheRegistryRecordBeforeDeletingItsTokenCases } from './npm-plugin.service.npm-plugin-service.removes-the-registry-record-before-deleting-its-token.test-cases';
import { registerInstallsStandardPackagePrefixedTarballsWithoutLosingConcurrentStateUpdatesCases } from './npm-plugin.service.npm-plugin-service.installs-standard-package-prefixed-tarballs-without-losing-concurrent-state-updates.test-cases';
import { registerPersistsAnExactPrivateRegistryInstallationAcrossServiceRestartCases } from './npm-plugin.service.npm-plugin-service.persists-an-exact-private-registry-installation-across-service-restart.test-cases';
import { registerClassifiesAnInstallationUsingTheSelectedVersionPublisherCases } from './npm-plugin.service.npm-plugin-service.classifies-an-installation-using-the-selected-version-publisher.test-cases';
import { registerDoesNotActivateConcurrentInstallsOfTheSamePackageCases } from './npm-plugin.service.npm-plugin-service.does-not-activate-concurrent-installs-of-the-same-package.test-cases';
import { registerResolvesSemverRangesWhilePersistingTheRequestedSpecCases } from './npm-plugin.service.npm-plugin-service.resolves-semver-ranges-while-persisting-the-requested-spec.test-cases';
import { registerRemovesNpmPackageCodeAndItsInstallationRecordWithoutRevertingMigrationsCases } from './npm-plugin.service.npm-plugin-service.removes-npm-package-code-and-its-installation-record-without-reverting-migrations.test-cases';
import { registerRestartsAfterRemovingAPackageWhenQuarantineCleanupFailsCases } from './npm-plugin.service.npm-plugin-service.restarts-after-removing-a-package-when-quarantine-cleanup-fails.test-cases';
import { registerKeepsARemovedNpmPluginQuarantinedWhenStatePersistenceFailsCases } from './npm-plugin.service.npm-plugin-service.keeps-a-removed-npm-plugin-quarantined-when-state-persistence-fails.test-cases';
import { registerRestartsAfterBackupCleanupFailsFollowingASuccessfulInstallCases } from './npm-plugin.service.npm-plugin-service.restarts-after-backup-cleanup-fails-following-a-successful-install.test-cases';
import { registerReturnsAQuarantinedInstallWhenQuarantineCleanupFailsCases } from './npm-plugin.service.npm-plugin-service.returns-a-quarantined-install-when-quarantine-cleanup-fails.test-cases';
import { registerKeepsAPluginQuarantinedWhenItsFinalActiveStateCannotBePersistedCases } from './npm-plugin.service.npm-plugin-service.keeps-a-plugin-quarantined-when-its-final-active-state-cannot-be-persisted.test-cases';
import { registerRollsBackAnActivationWhenItsQuarantineFallbackCannotBePersistedCases } from './npm-plugin.service.npm-plugin-service.rolls-back-an-activation-when-its-quarantine-fallback-cannot-be-persisted.test-cases';
import { registerRetriesRollbackAfterIsolatingAFailedActivationCases } from './npm-plugin.service.npm-plugin-service.retries-rollback-after-isolating-a-failed-activation.test-cases';
import { registerRestoresTheStateMatchingPackageAfterAnInterruptedReplacementCases } from './npm-plugin.service.npm-plugin-service.restores-the-state-matching-package-after-an-interrupted-replacement.test-cases';
import { registerReplacesNewlyActivatedCodeWithTheStateMatchingBackupAfterACrashCases } from './npm-plugin.service.npm-plugin-service.replaces-newly-activated-code-with-the-state-matching-backup-after-a-crash.test-cases';
import { registerSkipsBackupRecoveryWhenPluginsAreNotConfiguredCases } from './npm-plugin.service.npm-plugin-service.skips-backup-recovery-when-plugins-are-not-configured.test-cases';
import { registerFailsRecoveryWhenItCannotReconcileAPackageBackupCases } from './npm-plugin.service.npm-plugin-service.fails-recovery-when-it-cannot-reconcile-a-package-backup.test-cases';
import { registerClassifiesInstalledVersionsAndCalculatesTheirPermissionDeltaCases } from './npm-plugin.service.npm-plugin-service.classifies-installed-versions-and-calculates-their-permission-delta.test-cases';
import { registerClassifiesEachVersionUsingItsOwnPublisherMetadataCases } from './npm-plugin.service.npm-plugin-service.classifies-each-version-using-its-own-publisher-metadata.test-cases';
import { registerRequiresTheExactPermissionAdditionsBeforeReplacingAnInstalledPackageCases } from './npm-plugin.service.npm-plugin-service.requires-the-exact-permission-additions-before-replacing-an-installed-package.test-cases';
import { registerRejectsReplacingAnInstalledPackageThroughTheInstallEndpointCases } from './npm-plugin.service.npm-plugin-service.rejects-replacing-an-installed-package-through-the-install-endpoint.test-cases';
import { registerRequiresApprovalForPermissionsDeclaredByTheDownloadedReplacementTarballCases } from './npm-plugin.service.npm-plugin-service.requires-approval-for-permissions-declared-by-the-downloaded-replacement-tarball.test-cases';
import { registerRecordsAnAvailablePatchUpdateWithoutChangingTheRequestedRangeCases } from './npm-plugin.service.npm-plugin-service.records-an-available-patch-update-without-changing-the-requested-range.test-cases';
import { registerRequiresExplicitApprovalBeforeReplacingAnInstalledPackageWithAMajorVersionCases } from './npm-plugin.service.npm-plugin-service.requires-explicit-approval-before-replacing-an-installed-package-with-a-major-version.test-cases';
import { registerClassifiesAMajorPrereleaseAsAMajorUpdateCases } from './npm-plugin.service.npm-plugin-service.classifies-a-major-prerelease-as-a-major-update.test-cases';
import { registerAllowsPrereleaseCandidatesThatMatchAFollowRangeWhenEnabledByPolicyCases } from './npm-plugin.service.npm-plugin-service.allows-prerelease-candidates-that-match-a-follow-range-when-enabled-by-policy.test-cases';
import { registerFollowsAConfiguredDistTagWhenSelectingAnUpdateCandidateCases } from './npm-plugin.service.npm-plugin-service.follows-a-configured-dist-tag-when-selecting-an-update-candidate.test-cases';
import { registerSkipsRegistryUpdateChecksWhenChecksAreDisabledGloballyCases } from './npm-plugin.service.npm-plugin-service.skips-registry-update-checks-when-checks-are-disabled-globally.test-cases';
import { registerRecordsAFailedUpdateCheckWhenReadingTheUpdatePolicyFailsCases } from './npm-plugin.service.npm-plugin-service.records-a-failed-update-check-when-reading-the-update-policy-fails.test-cases';
import { registerPreservesConcurrentInstallPolicyChangesWhileRecordingAnUpdateCheckCases } from './npm-plugin.service.npm-plugin-service.preserves-concurrent-install-policy-changes-while-recording-an-update-check.test-cases';
import { registerRetriesAnUpdateCheckAfterTheGlobalPolicyChangesCases } from './npm-plugin.service.npm-plugin-service.retries-an-update-check-after-the-global-policy-changes.test-cases';
import { registerRetriesAFailedUpdateCheckAfterTheInstallationSpecChangesCases } from './npm-plugin.service.npm-plugin-service.retries-a-failed-update-check-after-the-installation-spec-changes.test-cases';
import { registerRetriesADistTagUpdateCheckAfterItsRequestedSpecChangesCases } from './npm-plugin.service.npm-plugin-service.retries-a-dist-tag-update-check-after-its-requested-spec-changes.test-cases';
import { registerUsesAnExplicitPerPluginUpdateModeInsteadOfTheGlobalModeCases } from './npm-plugin.service.npm-plugin-service.uses-an-explicit-per-plugin-update-mode-instead-of-the-global-mode.test-cases';
import { registerLimitsSimultaneousUpdateChecksToFourInstallationsCases } from './npm-plugin.service.npm-plugin-service.limits-simultaneous-update-checks-to-four-installations.test-cases';
describe('NpmPluginService', () => {
  const fixture = registerNpmPluginServiceFixture();
  registerCorrelatesAPersistedInstallWithItsSBootResultWithoutExposingAuditContextCases(fixture);
  registerPinsTarballDnsOnEverySameOriginRedirectAndReturnsArchiveBytesCases(fixture);
  registerRejectsTarballRedirectsWithoutDestinationsAcrossOriginsOrBeyondTheLimitCases(fixture);
  registerPinsMetadataRequestsToPublicRegistryAddressesAndLimitsTheirSizeCases(fixture);
  registerReturnsInvalidSearchCandidatesWithAnActionableIncompatibilityReasonCases(fixture);
  registerHydratesAbbreviatedSearchResultsBeforeValidatingMarketplacePackagesCases(fixture);
  registerReturnsAnAttestationUrlWhenTheRegistryProvidesPackageProvenanceCases(fixture);
  registerDiscoversPluginsThroughRegistryKeywordSearchWithoutAHardcodedPackageListCases(fixture);
  registerRetainsHydratedMarketplacePackagesWhenAnotherResultNoLongerHasMetadataCases(fixture);
  registerDoesNotTrustAPackageDeclaredOfficialFlagOrAMismatchedRegistryPublisherCases(fixture);
  registerRejectsMarketplaceMetadataThatClaimsAnAllowlistedPackageIdentityForADifferCases(fixture);
  registerUsesTheSelectedRegistryForDirectMarketplaceLookupCases(fixture);
  registerSearchesAConfiguredRegistryWhenItSupportsNpmSearchCases(fixture);
  registerRejectsMetadataRequestsToPrivateRegistryAddressesCases(fixture);
  registerDoesNotPersistARegistryWhenTokenStorageFailsCases(fixture);
  registerReturnsRegistryMetadataWithoutItsStoredTokenCases(fixture);
  registerRejectsRegistryAdditionsBeyondTheConfiguredRegistryLimitCases(fixture);
  registerPermitsRetryingRegistryTokenCleanupAfterItsRegistryRecordWasRemovedCases(fixture);
  registerPreservesARegistryTokenWhenRemovingItsRecordFailsCases(fixture);
  registerRemovesTheRegistryRecordBeforeDeletingItsTokenCases(fixture);
  registerInstallsStandardPackagePrefixedTarballsWithoutLosingConcurrentStateUpdatesCases(fixture);
  registerPersistsAnExactPrivateRegistryInstallationAcrossServiceRestartCases(fixture);
  registerClassifiesAnInstallationUsingTheSelectedVersionPublisherCases(fixture);
  registerDoesNotActivateConcurrentInstallsOfTheSamePackageCases(fixture);
  registerResolvesSemverRangesWhilePersistingTheRequestedSpecCases(fixture);
  registerRemovesNpmPackageCodeAndItsInstallationRecordWithoutRevertingMigrationsCases(fixture);
  registerRestartsAfterRemovingAPackageWhenQuarantineCleanupFailsCases(fixture);
  registerKeepsARemovedNpmPluginQuarantinedWhenStatePersistenceFailsCases(fixture);
  registerRestartsAfterBackupCleanupFailsFollowingASuccessfulInstallCases(fixture);
  registerReturnsAQuarantinedInstallWhenQuarantineCleanupFailsCases(fixture);
  registerKeepsAPluginQuarantinedWhenItsFinalActiveStateCannotBePersistedCases(fixture);
  registerRollsBackAnActivationWhenItsQuarantineFallbackCannotBePersistedCases(fixture);
  registerRetriesRollbackAfterIsolatingAFailedActivationCases(fixture);
  registerRestoresTheStateMatchingPackageAfterAnInterruptedReplacementCases(fixture);
  registerReplacesNewlyActivatedCodeWithTheStateMatchingBackupAfterACrashCases(fixture);
  registerSkipsBackupRecoveryWhenPluginsAreNotConfiguredCases(fixture);
  registerFailsRecoveryWhenItCannotReconcileAPackageBackupCases(fixture);
  registerClassifiesInstalledVersionsAndCalculatesTheirPermissionDeltaCases(fixture);
  registerClassifiesEachVersionUsingItsOwnPublisherMetadataCases(fixture);
  registerRequiresTheExactPermissionAdditionsBeforeReplacingAnInstalledPackageCases(fixture);
  registerRejectsReplacingAnInstalledPackageThroughTheInstallEndpointCases(fixture);
  registerRequiresApprovalForPermissionsDeclaredByTheDownloadedReplacementTarballCases(fixture);
  registerRecordsAnAvailablePatchUpdateWithoutChangingTheRequestedRangeCases(fixture);
  registerRequiresExplicitApprovalBeforeReplacingAnInstalledPackageWithAMajorVersionCases(fixture);
  registerClassifiesAMajorPrereleaseAsAMajorUpdateCases(fixture);
  registerAllowsPrereleaseCandidatesThatMatchAFollowRangeWhenEnabledByPolicyCases(fixture);
  registerFollowsAConfiguredDistTagWhenSelectingAnUpdateCandidateCases(fixture);
  registerSkipsRegistryUpdateChecksWhenChecksAreDisabledGloballyCases(fixture);
  registerRecordsAFailedUpdateCheckWhenReadingTheUpdatePolicyFailsCases(fixture);
  registerPreservesConcurrentInstallPolicyChangesWhileRecordingAnUpdateCheckCases(fixture);
  registerRetriesAnUpdateCheckAfterTheGlobalPolicyChangesCases(fixture);
  registerRetriesAFailedUpdateCheckAfterTheInstallationSpecChangesCases(fixture);
  registerRetriesADistTagUpdateCheckAfterItsRequestedSpecChangesCases(fixture);
  registerUsesAnExplicitPerPluginUpdateModeInsteadOfTheGlobalModeCases(fixture);
  registerLimitsSimultaneousUpdateChecksToFourInstallationsCases(fixture);
});
