import { registerNpmPluginDependencyLifecycleFixture } from './npm-plugin-dependencies.npm-plugin-dependency-lifecycle.test-fixture';
import { registerPreviewsDirectAndTransitiveDependenciesAndCommitsThemWithASingleConfirmatiCases } from './npm-plugin-dependencies.npm-plugin-dependency-lifecycle.blocks-incompatible-upgrades-and-downgrades-of-dependencies-and-dependants.behaviors.test-cases';
import { registerReusesACompatibleDependencyWithoutDownloadingOrReplacingItCases } from './npm-plugin-dependencies.npm-plugin-dependency-lifecycle.resolves-and-confirms-the-complete-dependency-tree-from-distribution-only-registry-me.behaviors.test-cases';
import { registerResolvesAndConfirmsTheCompleteDependencyTreeFromDistributionOnlyRegistryMeCases } from './npm-plugin-dependencies.npm-plugin-dependency-lifecycle.resolves-and-confirms-the-complete-dependency-tree-from-distribution-only-registry-me.behaviors.test-cases';
import { registerUsesTheRegistryPackagePublisherConsistentlyDuringPlanningAndInstallationCases } from './npm-plugin-dependencies.npm-plugin-dependency-lifecycle.resolves-and-confirms-the-complete-dependency-tree-from-distribution-only-registry-me.behaviors.test-cases';
import { registerInspectsOnlyTheFirstMatchingTarballReleaseNeededForADependencyPlanCases } from './npm-plugin-dependencies.npm-plugin-dependency-lifecycle.blocks-incompatible-upgrades-and-downgrades-of-dependencies-and-dependants.behaviors.test-cases';
import { registerInspectsAlternativeTarballReleasesLazilyWhenBacktrackingChangesDependencyRanCases } from './npm-plugin-dependencies.npm-plugin-dependency-lifecycle.blocks-incompatible-upgrades-and-downgrades-of-dependencies-and-dependants.behaviors.test-cases';
import { registerRejectsAStaleApprovalWhenRegistryPermissionsChangeCases } from './npm-plugin-dependencies.npm-plugin-dependency-lifecycle.blocks-incompatible-upgrades-and-downgrades-of-dependencies-and-dependants.behaviors.test-cases';
import { registerRejectsRegistryAndTarballDependencyMismatchesWithoutInstallingAnythingCases } from './npm-plugin-dependencies.npm-plugin-dependency-lifecycle.blocks-incompatible-upgrades-and-downgrades-of-dependencies-and-dependants.behaviors.test-cases';
import { registerRollsBackTheCompleteTreeWhenSFailsCases } from './npm-plugin-dependencies.npm-plugin-dependency-lifecycle.resolves-and-confirms-the-complete-dependency-tree-from-distribution-only-registry-me.behaviors.test-cases';
import { registerBlocksIncompatibleUpgradesAndDowngradesOfDependenciesAndDependantsCases } from './npm-plugin-dependencies.npm-plugin-dependency-lifecycle.blocks-incompatible-upgrades-and-downgrades-of-dependencies-and-dependants.behaviors.test-cases';
import { registerInstallsNewlyRequiredPluginsDuringAConfirmedUpdateRetainingExistingDependenCases } from './npm-plugin-dependencies.npm-plugin-dependency-lifecycle.blocks-incompatible-upgrades-and-downgrades-of-dependencies-and-dependants.behaviors.test-cases';
import { registerProtectsDependenciesAndRequiresTheExactTransitiveRemovalApprovalCases } from './npm-plugin-dependencies.npm-plugin-dependency-lifecycle.blocks-incompatible-upgrades-and-downgrades-of-dependencies-and-dependants.behaviors.test-cases';
import { registerRestoresAllFilesAndStateWhenGroupedRemovalFailsToPersistCases } from './npm-plugin-dependencies.npm-plugin-dependency-lifecycle.resolves-and-confirms-the-complete-dependency-tree-from-distribution-only-registry-me.behaviors.test-cases';
import { registerBlocksSubsequentStateChangesUntilACommittedTransactionJournalIsRecoveredCases } from './npm-plugin-dependencies.npm-plugin-dependency-lifecycle.blocks-incompatible-upgrades-and-downgrades-of-dependencies-and-dependants.behaviors.test-cases';
import { registerRecoversAGroupedFileTransactionAfterACrashCommittedSCases } from './npm-plugin-dependencies.npm-plugin-dependency-lifecycle.blocks-incompatible-upgrades-and-downgrades-of-dependencies-and-dependants.behaviors.test-cases';
describe('npm plugin dependency lifecycle', () => {
  const fixture = registerNpmPluginDependencyLifecycleFixture();
  registerPreviewsDirectAndTransitiveDependenciesAndCommitsThemWithASingleConfirmatiCases(fixture);
  registerReusesACompatibleDependencyWithoutDownloadingOrReplacingItCases(fixture);
  registerResolvesAndConfirmsTheCompleteDependencyTreeFromDistributionOnlyRegistryMeCases(fixture);
  registerUsesTheRegistryPackagePublisherConsistentlyDuringPlanningAndInstallationCases(fixture);
  registerInspectsOnlyTheFirstMatchingTarballReleaseNeededForADependencyPlanCases(fixture);
  registerInspectsAlternativeTarballReleasesLazilyWhenBacktrackingChangesDependencyRanCases(fixture);
  registerRejectsAStaleApprovalWhenRegistryPermissionsChangeCases(fixture);
  registerRejectsRegistryAndTarballDependencyMismatchesWithoutInstallingAnythingCases(fixture);
  registerRollsBackTheCompleteTreeWhenSFailsCases(fixture);
  registerBlocksIncompatibleUpgradesAndDowngradesOfDependenciesAndDependantsCases(fixture);
  registerInstallsNewlyRequiredPluginsDuringAConfirmedUpdateRetainingExistingDependenCases(fixture);
  registerProtectsDependenciesAndRequiresTheExactTransitiveRemovalApprovalCases(fixture);
  registerRestoresAllFilesAndStateWhenGroupedRemovalFailsToPersistCases(fixture);
  registerBlocksSubsequentStateChangesUntilACommittedTransactionJournalIsRecoveredCases(fixture);
  registerRecoversAGroupedFileTransactionAfterACrashCommittedSCases(fixture);
});
