import { PERMISSIONS } from './rbac-seed-permissions';
export const ROLES = [
  {
    key: 'user',
    name: 'User',
    description: 'Basic authenticated user with read-only access to resources',
    isSystemManaged: 1,
    isDefault: 1,
    permissions: ['resources.read'],
  },
  {
    key: 'resource-manager',
    name: 'Resource Manager',
    description: 'Can create, update, delete, and manage access to resources',
    isSystemManaged: 1,
    isDefault: 0,
    permissions: [
      'resources.read',
      'resources.create',
      'resources.update',
      'resources.delete',
      'resources.access.manage',
      'resources.maintenance.manage',
    ],
  },
  {
    key: 'user-manager',
    name: 'User Manager',
    description: 'Can manage users and their role assignments',
    isSystemManaged: 1,
    isDefault: 0,
    permissions: ['users.read', 'users.create', 'users.update', 'users.delete', 'users.roles.manage'],
  },
  {
    key: 'billing-manager',
    name: 'Billing Manager',
    description: 'Can read and manage billing information',
    isSystemManaged: 1,
    isDefault: 0,
    permissions: ['billing.read', 'billing.manage'],
  },
  {
    key: 'system-admin',
    name: 'System Administrator',
    description: 'Can manage system settings, SSO, and plugins',
    isSystemManaged: 1,
    isDefault: 0,
    permissions: ['system.settings.manage', 'system.sso.manage', 'system.plugins.manage'],
  },
  {
    key: 'owner',
    name: 'Owner',
    description: 'Has all permissions in the system',
    isSystemManaged: 1,
    isDefault: 0,
    permissions: PERMISSIONS.map((p) => p.key),
  },
];
