export enum ESPToolsErrorType {
  NO_PORT_SELECTED = 'NO_PORT_SELECTED',
  CONNECTION_FAILED = 'CONNECTION_FAILED',
  PORT_OPEN_FAILED = 'PORT_OPEN_FAILED',
  FLASH_FAILED = 'FLASH_FAILED',
  DEVICE_NOT_FOUND = 'DEVICE_NOT_FOUND',
  FIRMWARE_READ_FAILED = 'FIRMWARE_READ_FAILED',
  RESET_FAILED = 'RESET_FAILED',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  NO_TRANSPORT_AVAILABLE = 'NO_TRANSPORT_AVAILABLE',
}
