import { registerPasswordPolicyServiceFixture } from './password-policy.service.password-policy-service.test-fixture';
import { registerAuditsACommittedGlobalPolicyChangeWithBeforeAfterValuesAndActorAttributioCases } from './password-policy.service.password-policy-service.accepts-a-strong-password-hibp-clean-score-above-threshold.behaviors.test-cases';
import { registerAuditsRoleOverrideCreationAndDeletionWhileRetainingTheDeletedPolicySnapshoCases } from './password-policy.service.password-policy-service.accepts-a-strong-password-hibp-clean-score-above-threshold.behaviors.test-cases';
import { registerDoesNotEmitSuccessfulAuditRecordsWhenPolicyPersistenceFailsCases } from './password-policy.service.password-policy-service.accepts-a-strong-password-hibp-clean-score-above-threshold.behaviors.test-cases';
import { registerSeedsDefaultsWhenNoRowExistsCases } from './password-policy.service.password-policy-service.accepts-a-strong-password-hibp-clean-score-above-threshold.behaviors.test-cases';
import { registerReturnsSanitizedPublicPolicyWithoutInternalFlagsCases } from './password-policy.service.password-policy-service.accepts-a-strong-password-hibp-clean-score-above-threshold.behaviors.test-cases';
import { registerRejectsAWeakPasswordWithStructuredPolicyErrorsCases } from './password-policy.service.password-policy-service.accepts-a-strong-password-hibp-clean-score-above-threshold.behaviors.test-cases';
import { registerAcceptsAStrongPasswordHibpCleanScoreAboveThresholdCases } from './password-policy.service.password-policy-service.accepts-a-strong-password-hibp-clean-score-above-threshold.behaviors.test-cases';
import { registerReportsHibpPwnedWithCountCases } from './password-policy.service.password-policy-service.accepts-a-strong-password-hibp-clean-score-above-threshold.behaviors.test-cases';
import { registerSkipsHibpWhenPolicyCheckHibpIsFalseCases } from './password-policy.service.password-policy-service.accepts-a-strong-password-hibp-clean-score-above-threshold.behaviors.test-cases';
import { registerPasswordHistoryCases } from './password-policy.service.password-policy-service.accepts-a-strong-password-hibp-clean-score-above-threshold.behaviors.test-cases';
import { registerRoleOverridesCases } from './password-policy.service.password-policy-service.role-overrides.test-cases';
import { registerUpdatePolicyHotReloadCases } from './password-policy.service.password-policy-service.update-policy-hot-reload.test-cases';
describe('PasswordPolicyService', () => {
  const fixture = registerPasswordPolicyServiceFixture();
  registerAuditsACommittedGlobalPolicyChangeWithBeforeAfterValuesAndActorAttributioCases(fixture);
  registerAuditsRoleOverrideCreationAndDeletionWhileRetainingTheDeletedPolicySnapshoCases(fixture);
  registerDoesNotEmitSuccessfulAuditRecordsWhenPolicyPersistenceFailsCases(fixture);
  registerSeedsDefaultsWhenNoRowExistsCases(fixture);
  registerReturnsSanitizedPublicPolicyWithoutInternalFlagsCases(fixture);
  registerRejectsAWeakPasswordWithStructuredPolicyErrorsCases(fixture);
  registerAcceptsAStrongPasswordHibpCleanScoreAboveThresholdCases(fixture);
  registerReportsHibpPwnedWithCountCases(fixture);
  registerSkipsHibpWhenPolicyCheckHibpIsFalseCases(fixture);
  registerPasswordHistoryCases(fixture);
  registerRoleOverridesCases(fixture);
  registerUpdatePolicyHotReloadCases(fixture);
});
