import { registerResourceOperatingAttributionServiceFixture } from './resource-operating-attribution.service.resource-operating-attribution-service.test-fixture';
import { registerDerivesExactClosedIntersectionsAndTheRemainingOperatingDurationCases } from './resource-operating-attribution.service.resource-operating-attribution-service.calculates-a-completed-usage-session-from-its-exact-operating-overlap.behaviors.test-cases';
import { registerGetDurationsForWindowsCases } from './resource-operating-attribution.service.resource-operating-attribution-service.calculates-a-completed-usage-session-from-its-exact-operating-overlap.behaviors.test-cases';
import { registerMarksIntersectionsProvisionalWhileEitherSourceIntervalIsOpenCases } from './resource-operating-attribution.service.resource-operating-attribution-service.loads-and-derives-reports-for-multiple-resources-in-one-query-per-source.behaviors.test-cases';
import { registerMarksAnOtherwiseClosedOperatingIntervalProvisionalWhileItsUsageSessionRemaCases } from './resource-operating-attribution.service.resource-operating-attribution-service.loads-and-derives-reports-for-multiple-resources-in-one-query-per-source.behaviors.test-cases';
import { registerDoesNotAttributeAdjacentBoundariesCases } from './resource-operating-attribution.service.resource-operating-attribution-service.calculates-a-completed-usage-session-from-its-exact-operating-overlap.behaviors.test-cases';
import { registerRetainsTheGapBetweenTakeoverSessionsAsUnattributedCases } from './resource-operating-attribution.service.resource-operating-attribution-service.loads-and-derives-reports-for-multiple-resources-in-one-query-per-source.behaviors.test-cases';
import { registerDoesNotDoubleCountOperatingDurationWhenUsageSessionsOverlapCases } from './resource-operating-attribution.service.resource-operating-attribution-service.calculates-a-completed-usage-session-from-its-exact-operating-overlap.behaviors.test-cases';
import { registerSweepsIntervalEndpointsWithoutRevisitingExpiredSessionsCases } from './resource-operating-attribution.service.resource-operating-attribution-service.loads-and-derives-reports-for-multiple-resources-in-one-query-per-source.behaviors.test-cases';
import { registerDoesNotReportOverlapBetweenOperatingIntervalsAsUnattributedCases } from './resource-operating-attribution.service.resource-operating-attribution-service.calculates-a-completed-usage-session-from-its-exact-operating-overlap.behaviors.test-cases';
import { registerIgnoresDoorControlAuditRowsCases } from './resource-operating-attribution.service.resource-operating-attribution-service.calculates-a-completed-usage-session-from-its-exact-operating-overlap.behaviors.test-cases';
import { registerReportsNoDerivedDurationForResourcesWithoutAnOperatingSignalCases } from './resource-operating-attribution.service.resource-operating-attribution-service.loads-and-derives-reports-for-multiple-resources-in-one-query-per-source.behaviors.test-cases';
import { registerMarksASnapshotProvisionalForAnUnmatchedOpenUsageSessionCases } from './resource-operating-attribution.service.resource-operating-attribution-service.loads-and-derives-reports-for-multiple-resources-in-one-query-per-source.behaviors.test-cases';
import { registerClipsClosedIntervalsToTheAttributionSnapshotTimeCases } from './resource-operating-attribution.service.resource-operating-attribution-service.calculates-a-completed-usage-session-from-its-exact-operating-overlap.behaviors.test-cases';
import { registerDerivesAnExplicitDiagnosticsRangeThroughTheSameSweepAsTheDefaultWindowAtCases } from './resource-operating-attribution.service.resource-operating-attribution-service.calculates-a-completed-usage-session-from-its-exact-operating-overlap.behaviors.test-cases';
import { registerCalculatesACompletedUsageSessionFromItsExactOperatingOverlapCases } from './resource-operating-attribution.service.resource-operating-attribution-service.calculates-a-completed-usage-session-from-its-exact-operating-overlap.behaviors.test-cases';
import { registerLoadsOnlyIntervalsThatOverlapTheRecentAttributionWindowCases } from './resource-operating-attribution.service.resource-operating-attribution-service.loads-and-derives-reports-for-multiple-resources-in-one-query-per-source.behaviors.test-cases';
import { registerLoadsAndDerivesReportsForMultipleResourcesInOneQueryPerSourceCases } from './resource-operating-attribution.service.resource-operating-attribution-service.loads-and-derives-reports-for-multiple-resources-in-one-query-per-source.behaviors.test-cases';
describe('ResourceOperatingAttributionService', () => {
  const fixture = registerResourceOperatingAttributionServiceFixture();
  registerDerivesExactClosedIntersectionsAndTheRemainingOperatingDurationCases(fixture);
  registerGetDurationsForWindowsCases(fixture);
  registerMarksIntersectionsProvisionalWhileEitherSourceIntervalIsOpenCases(fixture);
  registerMarksAnOtherwiseClosedOperatingIntervalProvisionalWhileItsUsageSessionRemaCases(fixture);
  registerDoesNotAttributeAdjacentBoundariesCases(fixture);
  registerRetainsTheGapBetweenTakeoverSessionsAsUnattributedCases(fixture);
  registerDoesNotDoubleCountOperatingDurationWhenUsageSessionsOverlapCases(fixture);
  registerSweepsIntervalEndpointsWithoutRevisitingExpiredSessionsCases(fixture);
  registerDoesNotReportOverlapBetweenOperatingIntervalsAsUnattributedCases(fixture);
  registerIgnoresDoorControlAuditRowsCases(fixture);
  registerReportsNoDerivedDurationForResourcesWithoutAnOperatingSignalCases(fixture);
  registerMarksASnapshotProvisionalForAnUnmatchedOpenUsageSessionCases(fixture);
  registerClipsClosedIntervalsToTheAttributionSnapshotTimeCases(fixture);
  registerDerivesAnExplicitDiagnosticsRangeThroughTheSameSweepAsTheDefaultWindowAtCases(fixture);
  registerCalculatesACompletedUsageSessionFromItsExactOperatingOverlapCases(fixture);
  registerLoadsOnlyIntervalsThatOverlapTheRecentAttributionWindowCases(fixture);
  registerLoadsAndDerivesReportsForMultipleResourcesInOneQueryPerSourceCases(fixture);
});
