import { toMethodName, toEventName, toPascalCase } from './schema-tools';
import type { ChannelInfo } from './schema-tools';

export function renderClient(clientSends: ChannelInfo[], clientReceives: ChannelInfo[]): string {
  const sendTypes = clientSends.map((s) => s.schemaName).filter((n): n is string => !!n && n !== 'Object');
  const receiveTypes = clientReceives.map((s) => s.schemaName).filter((n): n is string => !!n && n !== 'Object');
  const uniqueTypes = [...sendTypes, ...receiveTypes].filter((v, i, a) => a.indexOf(v) === i);
  const typeImports = uniqueTypes.length > 0 ? `import type { ${uniqueTypes.join(', ')} } from './types';\n` : '';

  // EventEmitter overloads for subscribe channels (client receives)
  const onOverloads = clientReceives.map(({ channel, schemaName }) => {
    const event = toEventName(channel);
    const payloadType = schemaName && schemaName !== 'Object' ? schemaName : null;
    const listenerType = payloadType ? `(payload: ${payloadType}) => void` : `() => void`;
    return `  on(event: '${event}', listener: ${listenerType}): this;`;
  });
  onOverloads.push(`  on(event: 'connected', listener: () => void): this;`);
  onOverloads.push(`  on(event: 'disconnected', listener: () => void): this;`);

  // Send methods for publish channels (client sends)
  const sendMethods = clientSends.map(({ channel, schemaName }) => {
    const method = toMethodName(channel);
    const payloadType = schemaName && schemaName !== 'Object' ? schemaName : null;
    const param = payloadType ? `payload: ${payloadType}` : null;
    const sendArg = param ? `, payload` : `, {}`;
    return `  send${toPascalCase(method)}(${param ?? ''}) {\n    this.send('${channel}'${sendArg});\n  }`;
  });

  // Dispatch cases for subscribe channels (client receives)
  const dispatchCases = clientReceives.map(({ channel, schemaName }) => {
    const event = toEventName(channel);
    const hasPayload = !!(schemaName && schemaName !== 'Object');
    const emitArg = hasPayload ? ', data' : '';
    return `      case '${channel}':\n        this.emit('${event}'${emitArg});\n        break;`;
  });

  const clientTs = `// Auto-generated by libs/companion-ws-client/tools/generate.ts — do not edit
import WebSocket from 'ws';
import { EventEmitter } from 'events';
${typeImports}
// eslint-disable-next-line @typescript-eslint/no-unsafe-declaration-merging
export declare interface CompanionWsClient {
${onOverloads.join('\n')}
}

// eslint-disable-next-line @typescript-eslint/no-unsafe-declaration-merging
export class CompanionWsClient extends EventEmitter {
  private ws: WebSocket | null = null;
  private reconnectDelay = 2000;
  private readonly maxDelay = 60000;
  private stopped = false;
  private reconnectTimer: NodeJS.Timeout | null = null;

  constructor(private readonly serverUrl: string) {
    super();
  }

  connect() {
    this.stopped = false;
    this.reconnectDelay = 2000;
    this.openSocket();
  }

  private openSocket() {
    const url = this.serverUrl.replace(/^http/, 'ws') + '/api/companion/websocket';
    this.ws = new WebSocket(url);

    this.ws.on('open', () => {
      this.reconnectDelay = 2000;
      this.emit('connected');
    });

    this.ws.on('message', (raw) => {
      try {
        const msg = JSON.parse(raw.toString()) as { event: string; data: unknown };
        this.dispatch(msg.event, msg.data);
      } catch {
        // ignore malformed messages
      }
    });

    this.ws.on('close', () => {
      this.emit('disconnected');
      if (!this.stopped) this.scheduleReconnect();
    });

    this.ws.on('error', () => {
      // close fires after error; reconnect handled there
    });
  }

  private scheduleReconnect() {
    this.reconnectTimer = setTimeout(() => {
      this.reconnectTimer = null;
      this.openSocket();
    }, this.reconnectDelay);
    this.reconnectDelay = Math.min(this.reconnectDelay * 2, this.maxDelay);
  }

  stop() {
    this.stopped = true;
    if (this.reconnectTimer) {
      clearTimeout(this.reconnectTimer);
      this.reconnectTimer = null;
    }
    this.ws?.close();
  }

  // ─── Send methods (Client → Server) ──────────────────────────────────────
${sendMethods.join('\n\n')}

  private send(event: string, data: unknown) {
    if (this.ws?.readyState === WebSocket.OPEN) {
      this.ws.send(JSON.stringify({ event, data }));
    }
  }

  // ─── Receive dispatch (Server → Client) ──────────────────────────────────
  private dispatch(event: string, data: unknown) {
    switch (event) {
${dispatchCases.join('\n')}
    }
  }
}
`;

  return clientTs;
}
