/* eslint-disable no-console -- Preserve operational diagnostics and CLI output. */
import { renderClient } from './client-rendering';
import { mkdirSync, readFileSync, writeFileSync } from 'fs';
import { join, resolve } from 'path';
import { AsyncApiSpec, ChannelInfo, JsonSchema, jsonSchemaToTs, refName, resolveSchema } from './schema-tools';

// ─── AsyncAPI 2.x types ───────────────────────────────────────────────────────
// ─── Helpers ──────────────────────────────────────────────────────────────────
// ─── Main ─────────────────────────────────────────────────────────────────────

const specPath = resolve('dist/apps/api/asyncapi.json');
const outDir = resolve('libs/companion-ws-client/src/lib');

mkdirSync(outDir, { recursive: true });

const spec: AsyncApiSpec = JSON.parse(readFileSync(specPath, 'utf8'));
const schemas = spec.components?.schemas ?? {};
// Channels where the CLIENT sends (spec "publish" = client publishes to server)
const clientSends: ChannelInfo[] = [];
// Channels where the CLIENT receives (spec "subscribe" = client subscribes to server)
const clientReceives: ChannelInfo[] = [];

for (const [channel, ops] of Object.entries(spec.channels)) {
  if (ops.publish) {
    const payload = ops.publish.message?.payload;
    const schemaRef = payload && '$ref' in payload && payload.$ref ? refName(payload.$ref) : null;
    const schema = resolveSchema(payload, schemas);
    clientSends.push({ channel, schemaName: schemaRef, schema });
  }
  if (ops.subscribe) {
    const payload = ops.subscribe.message?.payload;
    const schemaRef = payload && '$ref' in payload && payload.$ref ? refName(payload.$ref) : null;
    const schema = resolveSchema(payload, schemas);
    clientReceives.push({ channel, schemaName: schemaRef, schema });
  }
}

// ─── Generate types.ts ────────────────────────────────────────────────────────

const emittedSchemas: string[] = [];

function collectReferencedSchemas(schema: JsonSchema | null): string[] {
  const refs: string[] = [];
  if (!schema) return refs;
  if (schema.$ref) refs.push(refName(schema.$ref));
  if (schema.properties) {
    for (const v of Object.values(schema.properties)) {
      const resolved = resolveSchema(v, schemas) ?? v;
      for (const r of collectReferencedSchemas(resolved)) refs.push(r);
    }
  }
  if (schema.items) {
    const resolved = resolveSchema(schema.items, schemas) ?? schema.items;
    for (const r of collectReferencedSchemas(resolved)) refs.push(r);
  }
  return refs;
}

const neededSchemasList: string[] = [];
for (const { schemaName, schema } of [...clientSends, ...clientReceives]) {
  if (schemaName && schemaName !== 'Object') neededSchemasList.push(schemaName);
  if (schema) {
    for (const r of collectReferencedSchemas(schema)) {
      if (r !== 'Object') neededSchemasList.push(r);
    }
  }
}
const neededSchemas = neededSchemasList.filter((v, i, a) => a.indexOf(v) === i);

let typesContent = `// Auto-generated by libs/companion-ws-client/tools/generate.ts — do not edit\n\n`;

function emitSchema(name: string) {
  if (emittedSchemas.indexOf(name) !== -1) return;
  emittedSchemas.push(name);
  const schema = schemas[name];
  if (!schema || !schema.properties) return;

  // emit dependencies first
  for (const v of Object.values(schema.properties)) {
    if ('$ref' in v && v.$ref) emitSchema(refName(v.$ref));
    else if (v.items && '$ref' in v.items && typeof v.items.$ref === 'string') emitSchema(refName(v.items.$ref));
  }

  const required = new Set(schema.required ?? []);
  const props = Object.entries(schema.properties).map(([k, v]) => {
    const opt = required.has(k) ? '' : '?';
    let typeStr: string;
    if ('$ref' in v && v.$ref) {
      typeStr = refName(v.$ref);
    } else if (v.type === 'array' && v.items) {
      // Preserve $ref name for array items rather than inlining the resolved schema
      typeStr =
        ('$ref' in v.items && v.items.$ref
          ? refName(v.items.$ref)
          : jsonSchemaToTs(resolveSchema(v.items, schemas) ?? v.items, schemas, 2)) + '[]';
    } else {
      typeStr = jsonSchemaToTs(v, schemas, 2);
    }
    const desc = v.description ? `  /** ${v.description} */\n` : '';
    return `${desc}  ${k}${opt}: ${typeStr};`;
  });
  typesContent += `export interface ${name} {\n${props.join('\n')}\n}\n\n`;
}

for (const name of neededSchemas) emitSchema(name);

writeFileSync(join(outDir, 'types.ts'), typesContent.trimEnd() + '\n');

// ─── Generate client.ts ───────────────────────────────────────────────────────

const clientTs = renderClient(clientSends, clientReceives);

writeFileSync(join(outDir, 'client.ts'), clientTs);

console.log(`Generated companion-ws-client in ${outDir}`);
