/* eslint-disable no-console */
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import * as path from 'path';

interface AsyncApiSchema {
  type?: string;
  description?: string;
  required?: string[];
  properties?: Record<string, AsyncApiSchema>;
  items?: AsyncApiSchema;
  $ref?: string;
  additionalProperties?: boolean;
}

interface AsyncApiMessage {
  name: string;
  payload: { $ref: string };
}

interface AsyncApiOperation {
  action: 'send' | 'receive';
  messages: Array<{ $ref: string }>;
}

interface AsyncApiSpec {
  operations: Record<string, AsyncApiOperation>;
  components: {
    messages: Record<string, AsyncApiMessage>;
    schemas: Record<string, AsyncApiSchema>;
  };
}

const specPath = path.resolve('dist/apps/api/asyncapi.json');
const outDir = path.resolve('libs/companion-ws-client/src/lib');

const spec: AsyncApiSpec = JSON.parse(readFileSync(specPath, 'utf8'));

// ─── Resolve $ref within the spec ────────────────────────────────────────────

function resolveRef<T>(ref: string): T {
  const parts = ref.replace('#/', '').split('/');
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let node: any = spec;
  for (const p of parts) node = node[p];
  return node as T;
}

// ─── Schema → TypeScript type string ─────────────────────────────────────────

function schemaToTs(schema: AsyncApiSchema, schemas: Record<string, AsyncApiSchema>): string {
  if (schema.$ref) {
    const name = schema.$ref.split('/').pop()!;
    return name;
  }
  switch (schema.type) {
    case 'integer':
      return 'number';
    case 'string':
      return 'string';
    case 'boolean':
      return 'boolean';
    case 'array':
      return schema.items ? `${schemaToTs(schema.items, schemas)}[]` : 'unknown[]';
    case 'object': {
      if (!schema.properties || Object.keys(schema.properties).length === 0) return 'Record<string, never>';
      const fields = Object.entries(schema.properties)
        .map(([k, v]) => {
          const required = schema.required?.includes(k) ?? false;
          const opt = required ? '' : '?';
          return `  ${k}${opt}: ${schemaToTs(v, schemas)};`;
        })
        .join('\n');
      return `{\n${fields}\n}`;
    }
    default:
      return 'unknown';
  }
}

// ─── Generate types.ts ────────────────────────────────────────────────────────

function generateTypes(): string {
  const { schemas } = spec.components;
  const lines: string[] = ['// Auto-generated by libs/companion-ws-client/tools/generate.ts — do not edit', ''];

  for (const [name, schema] of Object.entries(schemas)) {
    if (name === 'EmptyPayload') continue;
    lines.push(`export interface ${name} {`);
    if (schema.properties) {
      for (const [field, fSchema] of Object.entries(schema.properties)) {
        const required = schema.required?.includes(field) ?? false;
        const opt = required ? '' : '?';
        if (fSchema.description) lines.push(`  /** ${fSchema.description} */`);
        lines.push(`  ${field}${opt}: ${schemaToTs(fSchema, schemas)};`);
      }
    }
    lines.push('}', '');
  }

  return lines.join('\n');
}

// ─── Generate client.ts ───────────────────────────────────────────────────────

function generateClient(): string {
  const { operations, components } = spec;

  const sendOps: Array<{ eventName: string; schemaName: string }> = [];
  const receiveOps: Array<{ eventName: string; schemaName: string }> = [];

  for (const [opName, op] of Object.entries(operations)) {
    const msgRef = op.messages[0].$ref;
    const msgName = msgRef.split('/').pop()!;
    const msg = components.messages[msgName];
    const schemaName = msg.payload.$ref.split('/').pop()!;

    if (op.action === 'send') {
      sendOps.push({ eventName: opName, schemaName });
    } else {
      receiveOps.push({ eventName: opName, schemaName });
    }
  }

  const importTypes = Array.from(new Set([...sendOps, ...receiveOps].map((o) => o.schemaName).filter((s) => s !== 'EmptyPayload')));

  const lines: string[] = [
    '// Auto-generated by libs/companion-ws-client/tools/generate.ts — do not edit',
    "import WebSocket from 'ws';",
    "import { EventEmitter } from 'events';",
  ];

  if (importTypes.length > 0) {
    lines.push(`import type { ${importTypes.join(', ')} } from './types';`);
  }

  lines.push('', '// ─── Typed event emitter declaration merge ───────────────────────────────────', '');
  lines.push('// eslint-disable-next-line @typescript-eslint/no-unsafe-declaration-merging');
  lines.push('export declare interface CompanionWsClient {');

  // Receive ops become emitted events that callers can listen to
  for (const { eventName, schemaName } of receiveOps) {
    const camelEvent = eventName.replace(/^COMPANION_/, '').toLowerCase();
    const listenerArg = schemaName !== 'EmptyPayload' ? `payload: ${schemaName}` : '';
    lines.push(`  on(event: '${camelEvent}', listener: (${listenerArg}) => void): this;`);
  }

  lines.push(
    "  on(event: 'connected', listener: () => void): this;",
    "  on(event: 'disconnected', listener: () => void): this;",
    '}',
    '',
    '// eslint-disable-next-line @typescript-eslint/no-unsafe-declaration-merging',
    'export class CompanionWsClient extends EventEmitter {',
    '  private ws: WebSocket | null = null;',
    '  private reconnectDelay = 2000;',
    '  private readonly maxDelay = 60000;',
    '  private stopped = false;',
    '  private reconnectTimer: NodeJS.Timeout | null = null;',
    '',
    '  constructor(private readonly serverUrl: string) {',
    '    super();',
    '  }',
    '',
    '  connect() {',
    '    this.stopped = false;',
    '    this.reconnectDelay = 2000;',
    '    this.openSocket();',
    '  }',
    '',
    "  private openSocket() {",
    "    const url = this.serverUrl.replace(/^http/, 'ws') + '/api/companion/websocket';",
    '    this.ws = new WebSocket(url);',
    '',
    "    this.ws.on('open', () => {",
    '      this.reconnectDelay = 2000;',
    "      this.emit('connected');",
    '    });',
    '',
    "    this.ws.on('message', (raw) => {",
    '      try {',
    "        const msg = JSON.parse(raw.toString()) as { event: string; data: unknown };",
    '        this.dispatch(msg.event, msg.data);',
    '      } catch {',
    '        // ignore malformed messages',
    '      }',
    '    });',
    '',
    "    this.ws.on('close', () => {",
    "      this.emit('disconnected');",
    '      if (!this.stopped) this.scheduleReconnect();',
    '    });',
    '',
    "    this.ws.on('error', () => {",
    '      // close fires after error; reconnect handled there',
    '    });',
    '  }',
    '',
    '  private scheduleReconnect() {',
    '    this.reconnectTimer = setTimeout(() => {',
    '      this.reconnectTimer = null;',
    '      this.openSocket();',
    '    }, this.reconnectDelay);',
    '    this.reconnectDelay = Math.min(this.reconnectDelay * 2, this.maxDelay);',
    '  }',
    '',
    '  stop() {',
    '    this.stopped = true;',
    '    if (this.reconnectTimer) {',
    '      clearTimeout(this.reconnectTimer);',
    '      this.reconnectTimer = null;',
    '    }',
    '    this.ws?.close();',
    '  }',
    '',
    '  // ─── Send methods (Client → Server) ──────────────────────────────────────',
  );

  for (const { eventName, schemaName } of sendOps) {
    const words = eventName.replace(/^COMPANION_/, '').split('_');
    const methodName = 'send' + words.map((w) => w[0] + w.slice(1).toLowerCase()).join('');
    if (schemaName !== 'EmptyPayload') {
      lines.push(`  ${methodName}(payload: ${schemaName}) {`);
      lines.push(`    this.send('${eventName}', payload);`);
    } else {
      lines.push(`  ${methodName}() {`);
      lines.push(`    this.send('${eventName}', {});`);
    }
    lines.push('  }', '');
  }

  lines.push(
    "  private send(event: string, data: unknown) {",
    '    if (this.ws?.readyState === WebSocket.OPEN) {',
    '      this.ws.send(JSON.stringify({ event, data }));',
    '    }',
    '  }',
    '',
    '  // ─── Receive dispatch (Server → Client) ──────────────────────────────────',
    '',
    '  private dispatch(event: string, data: unknown) {',
    '    switch (event) {',
  );

  for (const { eventName, schemaName } of receiveOps) {
    const camelEvent = eventName.replace(/^COMPANION_/, '').toLowerCase();
    lines.push(`      case '${eventName}':`);
    if (schemaName !== 'EmptyPayload') {
      lines.push(`        this.emit('${camelEvent}', data as ${schemaName});`);
    } else {
      lines.push(`        this.emit('${camelEvent}');`);
    }
    lines.push('        break;');
  }

  lines.push('    }', '  }', '}', '');

  return lines.join('\n');
}

// ─── Write output ─────────────────────────────────────────────────────────────

mkdirSync(outDir, { recursive: true });
writeFileSync(path.join(outDir, 'types.ts'), generateTypes());
writeFileSync(path.join(outDir, 'client.ts'), generateClient());
console.log(`Generated companion-ws-client in ${outDir}`);
