import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ALL_CONNECTORS } from '../connectors';
import type { ConnectorSpec } from '../connectors';

const HEADER = `<!-- DO NOT EDIT. Generated by \`pnpm nx run attractap-hw-shared:doc-gen\` from src/connectors/. -->

# Attractap Hardware Connector Pinouts

This file is the **freeze point** for the interconnect contract between
all Attractap V2 boards. Any pin reassignment requires a semver-major
bump on \`@attraccess/attractap-hw-shared\` and must be called out in the
PR description.

`;

function renderConnector(connector: ConnectorSpec): string {
  const lines: string[] = [];
  lines.push(`## ${connector.name}`);
  lines.push('');
  lines.push(`- Footprint: \`${connector.footprint}\``);
  lines.push(`- Pitch: ${connector.pitch}`);
  lines.push(`- Pin count: ${connector.pinCount}`);
  lines.push(`- Power pins (expected): ${connector.expectedPowerPins}`);
  lines.push(`- Ground pins (expected): ${connector.expectedGndPins}`);
  lines.push('');
  lines.push('| Pin | Signal | Direction | Voltage | Notes |');
  lines.push('| --- | --- | --- | --- | --- |');
  const pinNumbers = Object.keys(connector.pins)
    .map((p) => Number.parseInt(p, 10))
    .sort((a, b) => a - b);
  for (const pin of pinNumbers) {
    const def = connector.pins[pin];
    const voltage = def.voltage ?? '';
    const notes = def.notes ?? '';
    lines.push(`| ${pin} | \`${def.signal}\` | ${def.direction} | ${voltage} | ${notes} |`);
  }
  lines.push('');
  lines.push(
    `**Required signals:** ${connector.requiredSignals
      .map((s) => `\`${s}\``)
      .join(', ')}`,
  );
  lines.push('');
  return lines.join('\n');
}

function render(): string {
  const body = ALL_CONNECTORS.map(renderConnector).join('\n');
  return `${HEADER}${body}`;
}

const here = fileURLToPath(import.meta.url);
const projectRoot = resolve(here, '..', '..', '..');
const outputPath = resolve(projectRoot, 'CONNECTORS.md');

const isCheck = process.argv.includes('--check');
const next = render();

if (isCheck) {
  if (!existsSync(outputPath)) {
    process.stderr.write(`CONNECTORS.md missing at ${outputPath}\n`);
    process.exit(1);
  }
  const current = readFileSync(outputPath, 'utf8');
  if (current !== next) {
    process.stderr.write(
      'CONNECTORS.md is out of sync with src/connectors/. Run `pnpm nx run attractap-hw-shared:doc-gen` and commit the result.\n',
    );
    process.exit(1);
  }
  process.stdout.write('CONNECTORS.md in sync.\n');
} else {
  writeFileSync(outputPath, next);
  process.stdout.write(`Wrote ${outputPath}\n`);
}
