import { registerBillingControllerFixture } from './billing.controller.billing-controller.test-fixture';
import { registerShouldBeDefinedCases } from './billing.controller.billing-controller.create-manual-transaction.behaviors.test-cases';
import { registerGetBillingBalanceCases } from './billing.controller.billing-controller.create-manual-transaction.behaviors.test-cases';
import { registerGetBillingTransactionCases } from './billing.controller.billing-controller.create-manual-transaction.behaviors.test-cases';
import { registerScopesTheUsageToBillingLookupToTheRequesterIncludingBillingManagersCases } from './billing.controller.billing-controller.create-manual-transaction.behaviors.test-cases';
import { registerGetBillingTransactionsCases } from './billing.controller.billing-controller.create-manual-transaction.behaviors.test-cases';
import { registerCreateManualTransactionCases } from './billing.controller.billing-controller.create-manual-transaction.behaviors.test-cases';
import { registerGetResourceBillingConfigurationCases } from './billing.controller.billing-controller.create-manual-transaction.behaviors.test-cases';
import { registerUpdateResourceBillingConfigurationCases } from './billing.controller.billing-controller.top-up-with-sum-up-reader.behaviors.test-cases';
import { registerSetSumUpApiKeyCases } from './billing.controller.billing-controller.create-manual-transaction.behaviors.test-cases';
import { registerSetBillingConfigurationCases } from './billing.controller.billing-controller.create-manual-transaction.behaviors.test-cases';
import { registerGetBillingConfigurationCases } from './billing.controller.billing-controller.create-manual-transaction.behaviors.test-cases';
import { registerGetSumUpConfigurationCases } from './billing.controller.billing-controller.create-manual-transaction.behaviors.test-cases';
import { registerGetSumUpReadersCases } from './billing.controller.billing-controller.create-manual-transaction.behaviors.test-cases';
import { registerPairSumUpReaderCases } from './billing.controller.billing-controller.create-manual-transaction.behaviors.test-cases';
import { registerRemoveSumUpReaderCases } from './billing.controller.billing-controller.create-manual-transaction.behaviors.test-cases';
import { registerTopUpWithSumUpReaderCases } from './billing.controller.billing-controller.top-up-with-sum-up-reader.behaviors.test-cases';
import { registerSumUpTopUpCallbackCases } from './billing.controller.billing-controller.create-manual-transaction.behaviors.test-cases';
import { registerStreamEventsCases } from './billing.controller.billing-controller.create-manual-transaction.behaviors.test-cases';
describe('BillingController', () => {
  const fixture = registerBillingControllerFixture();
  registerShouldBeDefinedCases(fixture);
  registerGetBillingBalanceCases(fixture);
  registerGetBillingTransactionCases(fixture);
  registerScopesTheUsageToBillingLookupToTheRequesterIncludingBillingManagersCases(fixture);
  registerGetBillingTransactionsCases(fixture);
  registerCreateManualTransactionCases(fixture);
  registerGetResourceBillingConfigurationCases(fixture);
  registerUpdateResourceBillingConfigurationCases(fixture);
  registerSetSumUpApiKeyCases(fixture);
  registerSetBillingConfigurationCases(fixture);
  registerGetBillingConfigurationCases(fixture);
  registerGetSumUpConfigurationCases(fixture);
  registerGetSumUpReadersCases(fixture);
  registerPairSumUpReaderCases(fixture);
  registerRemoveSumUpReaderCases(fixture);
  registerTopUpWithSumUpReaderCases(fixture);
  registerSumUpTopUpCallbackCases(fixture);
  registerStreamEventsCases(fixture);
});
