import { registerBillingServiceFixture } from './billing.service.billing-service.test-fixture';
import { registerGetTransactionCases } from './billing.service.billing-service.get-resource-billing-configuration.behaviors.test-cases';
import { registerFindsOnlyTheOwnerSTransactionIdForAUsageSCases } from './billing.service.billing-service.configuration-currency.behaviors.test-cases';
import { registerCreatesAnOppositeSignRefundForTransactionAmountSCases } from './billing.service.billing-service.configuration-currency.behaviors.test-cases';
import { registerRejectsAbsentTransactionsAndInvalidRefundAmountsBeforeWritingCases } from './billing.service.billing-service.get-resource-billing-configuration.behaviors.test-cases';
import { registerShouldBeDefinedCases } from './billing.service.billing-service.get-resource-billing-configuration.behaviors.test-cases';
import { registerGetBalanceCases } from './billing.service.billing-service.configuration-currency.behaviors.test-cases';
import { registerGetHistoryCases } from './billing.service.billing-service.configuration-currency.behaviors.test-cases';
import { registerCreateManualTransactionCases } from './billing.service.billing-service.configuration-currency.behaviors.test-cases';
import { registerHandleResourceSessionStartedEventCases } from './billing.service.billing-service.handle-resource-session-started-event.behaviors.test-cases';
import { registerGetResourceBillingConfigurationCases } from './billing.service.billing-service.get-resource-billing-configuration.behaviors.test-cases';
import { registerHandleResourceUsageStartCases } from './billing.service.billing-service.get-resource-billing-configuration.behaviors.test-cases';
import { registerUpdateResourceBillingConfigurationCases } from './billing.service.billing-service.update-resource-billing-configuration.test-cases';
import { registerConfigurationCurrencyCases } from './billing.service.billing-service.configuration-currency.behaviors.test-cases';
import { registerBillingServiceChargeForResourceUsageCases } from './billing.service.billing-service.billing-service-charge-for-resource-usage.test-cases';
describe('BillingService', () => {
  const fixture = registerBillingServiceFixture();
  registerGetTransactionCases(fixture);
  registerFindsOnlyTheOwnerSTransactionIdForAUsageSCases(fixture);
  registerCreatesAnOppositeSignRefundForTransactionAmountSCases(fixture);
  registerRejectsAbsentTransactionsAndInvalidRefundAmountsBeforeWritingCases(fixture);
  registerShouldBeDefinedCases(fixture);
  registerGetBalanceCases(fixture);
  registerGetHistoryCases(fixture);
  registerCreateManualTransactionCases(fixture);
  registerHandleResourceSessionStartedEventCases(fixture);
  registerGetResourceBillingConfigurationCases(fixture);
  registerHandleResourceUsageStartCases(fixture);
  registerUpdateResourceBillingConfigurationCases(fixture);
  registerConfigurationCurrencyCases(fixture);
  registerBillingServiceChargeForResourceUsageCases(fixture);
});
