import { registerSumUpServiceFixture } from './sumup.service.sum-up-service.test-fixture';
import { registerSetApiKeyCases } from './sumup.service.sum-up-service.set-api-key.behaviors.test-cases';
import { registerGetIsEnabledCases } from './sumup.service.sum-up-service.get-is-enabled.behaviors.test-cases';
import { registerGetMerchantCases } from './sumup.service.sum-up-service.get-is-enabled.behaviors.test-cases';
import { registerGetReadersCases } from './sumup.service.sum-up-service.get-is-enabled.behaviors.test-cases';
import { registerPairReaderCases } from './sumup.service.sum-up-service.get-is-enabled.behaviors.test-cases';
import { registerRemoveReaderCases } from './sumup.service.sum-up-service.get-is-enabled.behaviors.test-cases';
import { registerTopUpWithReaderCases } from './sumup.service.sum-up-service.set-api-key.behaviors.test-cases';
import { registerHandleTransactionCallbackCases } from './sumup.service.sum-up-service.get-is-enabled.behaviors.test-cases';
import { registerUpdateTransactionStatusBySumupServerPrivateCases } from './sumup.service.sum-up-service.set-api-key.behaviors.test-cases';
import { registerProcessPendingTransactionsCases } from './sumup.service.sum-up-service.get-is-enabled.behaviors.test-cases';
describe('SumUpService', () => {
  const fixture = registerSumUpServiceFixture();
  registerSetApiKeyCases(fixture);
  registerGetIsEnabledCases(fixture);
  registerGetMerchantCases(fixture);
  registerGetReadersCases(fixture);
  registerPairReaderCases(fixture);
  registerRemoveReaderCases(fixture);
  registerTopUpWithReaderCases(fixture);
  registerHandleTransactionCallbackCases(fixture);
  registerUpdateTransactionStatusBySumupServerPrivateCases(fixture);
  registerProcessPendingTransactionsCases(fixture);
});
