import { registerSupervisionServiceFixture } from './supervision.service.supervision-service.test-fixture';
import { registerValidatesEagerlyAndEmitsARequestedEventToTheSelectedSupervisorCases } from './supervision.service.supervision-service.allows-multiple-parallel-pending-requests-for-the-same-supervisor-no-limit.behaviors.test-cases';
import { registerPropagatesValidationErrorsWithoutCreatingAPendingRequestCases } from './supervision.service.supervision-service.allows-multiple-parallel-pending-requests-for-the-same-supervisor-no-limit.behaviors.test-cases';
import { registerStartsTheSessionOnApprovalAndResolvesTheRequesterCases } from './supervision.service.supervision-service.allows-multiple-parallel-pending-requests-for-the-same-supervisor-no-limit.behaviors.test-cases';
import { registerRejectsTheRequesterWhenTheSupervisorRejectsTheRequestCases } from './supervision.service.supervision-service.allows-multiple-parallel-pending-requests-for-the-same-supervisor-no-limit.behaviors.test-cases';
import { registerExpiresTheRequestAfter30sAndTimesOutTheRequesterCases } from './supervision.service.supervision-service.allows-multiple-parallel-pending-requests-for-the-same-supervisor-no-limit.behaviors.test-cases';
import { registerRejectsApprovalFromSomeoneOtherThanTheRequestedSupervisorCases } from './supervision.service.supervision-service.allows-multiple-parallel-pending-requests-for-the-same-supervisor-no-limit.behaviors.test-cases';
import { registerThrowsNotFoundForAnUnknownOrAlreadySettledRequestCases } from './supervision.service.supervision-service.allows-multiple-parallel-pending-requests-for-the-same-supervisor-no-limit.behaviors.test-cases';
import { registerPropagatesAFailedSessionStartToBothSupervisorAndRequesterCases } from './supervision.service.supervision-service.allows-multiple-parallel-pending-requests-for-the-same-supervisor-no-limit.behaviors.test-cases';
import { registerAllowsMultipleParallelPendingRequestsForTheSameSupervisorNoLimitCases } from './supervision.service.supervision-service.allows-multiple-parallel-pending-requests-for-the-same-supervisor-no-limit.behaviors.test-cases';
import { registerReaderOriginatedRequestsAtt493Cases } from './supervision.service.supervision-service.reader-originated-requests-att-493.test-cases';
import { registerWebInitiatedReaderRequestsAtt816Cases } from './supervision.service.supervision-service.web-initiated-reader-requests-att-816.test-cases';
describe('SupervisionService', () => {
  const fixture = registerSupervisionServiceFixture();
  registerValidatesEagerlyAndEmitsARequestedEventToTheSelectedSupervisorCases(fixture);
  registerPropagatesValidationErrorsWithoutCreatingAPendingRequestCases(fixture);
  registerStartsTheSessionOnApprovalAndResolvesTheRequesterCases(fixture);
  registerRejectsTheRequesterWhenTheSupervisorRejectsTheRequestCases(fixture);
  registerExpiresTheRequestAfter30sAndTimesOutTheRequesterCases(fixture);
  registerRejectsApprovalFromSomeoneOtherThanTheRequestedSupervisorCases(fixture);
  registerThrowsNotFoundForAnUnknownOrAlreadySettledRequestCases(fixture);
  registerPropagatesAFailedSessionStartToBothSupervisorAndRequesterCases(fixture);
  registerAllowsMultipleParallelPendingRequestsForTheSameSupervisorNoLimitCases(fixture);
  registerReaderOriginatedRequestsAtt493Cases(fixture);
  registerWebInitiatedReaderRequestsAtt816Cases(fixture);
});
