import { useCommissioningClose } from './useCommissioningClose';

export function useCommissioningOutput(model: ReturnType<typeof useCommissioningClose>) {
  return {
    isOpen: model.isOpen,
    onConfigure: model.onConfigure,
    session: model.session,
    commissioningSessionsQuery: model.commissioningSessionsQuery,
    isLoading: model.isLoading,
    activeStep: model.activeStep,
    title: model.title,
    loadingStatus: model.loadingStatus,
    name: model.name,
    setName: model.setName,
    controllerIp: model.controllerIp,
    setControllerIp: model.setControllerIp,
    mqttServerId: model.mqttServerId,
    setMqttServerId: model.setMqttServerId,
    mqttServersQuery: model.mqttServersQuery,
    setArtifactBusy: model.setArtifactBusy,
    artifactBusy: model.artifactBusy,
    artifactAvailable: model.artifactAvailable,
    selectedMqttServerId: model.selectedMqttServerId,
    setSelectedArtifact: model.setSelectedArtifact,
    hostKeyFingerprint: model.hostKeyFingerprint,
    setHostKeyFingerprint: model.setHostKeyFingerprint,
    deliverSessionMutation: model.deliverSessionMutation,
    sshUsername: model.sshUsername,
    sshPassword: model.sshPassword,
    setSshUsername: model.setSshUsername,
    setSshPassword: model.setSshPassword,
    customSsh: model.customSsh,
    setCustomSsh: model.setCustomSsh,
    recoveryUsername: model.recoveryUsername,
    recoveryPassword: model.recoveryPassword,
    setRecoveryUsername: model.setRecoveryUsername,
    setRecoveryPassword: model.setRecoveryPassword,
    customRecoverySsh: model.customRecoverySsh,
    setCustomRecoverySsh: model.setCustomRecoverySsh,
    createSessionMutation: model.createSessionMutation,
    confirmHostKeyMutation: model.confirmHostKeyMutation,
    removeSessionMutation: model.removeSessionMutation,
    recoverSessionMutation: model.recoverSessionMutation,
    isCancelConfirmationOpen: model.isCancelConfirmationOpen,
    setCancelConfirmationOpen: model.setCancelConfirmationOpen,
    setStep: model.setStep,
    close: model.close,
    createSession: model.createSession,
    deliverSession: model.deliverSession,
    recoverSession: model.recoverSession,
    confirmHostKey: model.confirmHostKey,
    configureController: model.configureController,
  };
}
