# Attractap Lite: Adafruit Qualia S3 board, headless (no display), WS2812
# 24-LED status ring, W5500 SPI ethernet.
set(ATTRACTAP_FIRMWARE_NAME "attractap_lite")
set(ATTRACTAP_FIRMWARE_FRIENDLY_NAME "Attractap Lite")
set(ATTRACTAP_FIRMWARE_VARIANT "ethernet")
set(ATTRACTAP_FIRMWARE_VARIANT_FRIENDLY_NAME "Ethernet")

set(ATTRACTAP_DEFINES
    FIRMWARE_NAME="${ATTRACTAP_FIRMWARE_NAME}"
    FIRMWARE_FRIENDLY_NAME="${ATTRACTAP_FIRMWARE_FRIENDLY_NAME}"
    FIRMWARE_VARIANT="${ATTRACTAP_FIRMWARE_VARIANT}"
    FIRMWARE_VARIANT_FRIENDLY_NAME="${ATTRACTAP_FIRMWARE_VARIANT_FRIENDLY_NAME}"

    HAS_WS2812_LED=1
    PIN_WS2812_DATA=38
    WS2812_LED_COUNT=24
    USE_CIRCULAR_LED_RING=1

    LOGGER_LEVEL_NUM=3

    PIN_NFC_I2C_SDA=48
    PIN_NFC_I2C_SCL=47

    PIN_ETH_SPI_CS=14
    PIN_W5500_INT=10
    PIN_W5500_RESET=9
    PIN_ETH_SPI_MOSI=11
    PIN_ETH_SPI_MISO=12
    PIN_ETH_SPI_SCK=13

    BEEPER_PIN=21
)

set(ATTRACTAP_EXCLUDE_REGEX "src/(display|ioexpander)/")
