# Attractap Touch (V3 hardware): ESP32-S3 DevKitC, ST7701 480x480 RGB panel,
# GT911 touch, TCA9554 8-bit IO expander @0x20, PN532 NFC, WiFi.
set(ATTRACTAP_FIRMWARE_NAME "attractap_touch")
set(ATTRACTAP_FIRMWARE_FRIENDLY_NAME "Attractap Touch")
set(ATTRACTAP_FIRMWARE_VARIANT "wifi")
set(ATTRACTAP_FIRMWARE_VARIANT_FRIENDLY_NAME "WiFi")

set(ATTRACTAP_DEFINES
    FIRMWARE_NAME="${ATTRACTAP_FIRMWARE_NAME}"
    FIRMWARE_FRIENDLY_NAME="${ATTRACTAP_FIRMWARE_FRIENDLY_NAME}"
    FIRMWARE_VARIANT="${ATTRACTAP_FIRMWARE_VARIANT}"
    FIRMWARE_VARIANT_FRIENDLY_NAME="${ATTRACTAP_FIRMWARE_VARIANT_FRIENDLY_NAME}"

    LOGGER_LEVEL_NUM=3

    PIN_NFC_I2C_SDA=15
    PIN_NFC_I2C_SCL=7
    PIN_TOUCH_I2C_SDA=15
    PIN_TOUCH_I2C_SCL=7

    # No ethernet on this board (runtime-checked in ethernet.cpp)
    PIN_ETH_SPI_CS=-1
    PIN_W5500_INT=-1
    PIN_W5500_RESET=-1
    PIN_ETH_SPI_MOSI=-1
    PIN_ETH_SPI_MISO=-1
    PIN_ETH_SPI_SCK=-1

    HAS_LVGL_DISPLAY=1
    DISPLAY_DRIVER_GT911=1
    HAS_IO_EXPANDER=1
)

set(ATTRACTAP_EXCLUDE_REGEX "src/display/driver/qualia/")
