import { registerResourceUsageServiceFixture } from './resourceUsage.service.resource-usage-service.test-fixture';
import { registerAssignsAndClearsACompletedSessionProjectThroughTheOwningUserCases } from './resourceUsage.service.resource-usage-service.assigns-and-clears-a-completed-session-project-through-the-owning-user.behaviors.test-cases';
import { registerRejectsInvalidOrUnauthorizedProjectAssignmentsWithoutWritingTheSessionCases } from './resourceUsage.service.resource-usage-service.assigns-and-clears-a-completed-session-project-through-the-owning-user.behaviors.test-cases';
import { registerGetSessionDetailsCases } from './resourceUsage.service.resource-usage-service.assigns-and-clears-a-completed-session-project-through-the-owning-user.behaviors.test-cases';
import { registerStartSessionCases } from './resourceUsage.service.resource-usage-service.start-session.behaviors.test-cases';
import { registerSupervisedStartCases } from './resourceUsage.service.resource-usage-service.supervised-start.test-cases';
import { registerGetActiveSessionCases } from './resourceUsage.service.resource-usage-service.assigns-and-clears-a-completed-session-project-through-the-owning-user.behaviors.test-cases';
import { registerEndSessionCases } from './resourceUsage.service.endsession.should-end-session-successfully.behaviors.test-cases';
import { registerDoorActionsCases } from './resourceUsage.service.resource-usage-service.door-actions.test-cases';
import { registerCanControllResourceCacheCases } from './resourceUsage.service.resource-usage-service.can-controll-resource-cache.test-cases';
describe('ResourceUsageService', () => {
  const fixture = registerResourceUsageServiceFixture();
  registerAssignsAndClearsACompletedSessionProjectThroughTheOwningUserCases(fixture);
  registerRejectsInvalidOrUnauthorizedProjectAssignmentsWithoutWritingTheSessionCases(fixture);
  registerGetSessionDetailsCases(fixture);
  registerStartSessionCases(fixture);
  registerSupervisedStartCases(fixture);
  registerGetActiveSessionCases(fixture);
  registerEndSessionCases(fixture);
  registerDoorActionsCases(fixture);
  registerCanControllResourceCacheCases(fixture);
});
