import {
  BillingTransaction,
  BillingTransactionItem,
  FormSubmission,
  Project,
  Resource,
  ResourceOperatingInterval,
  ResourceUsage,
  ResourceUsageAction,
  ResourceUsageLifecycleAttempt,
  User,
} from '@attraccess/database-entities';
import { EntitySchema } from 'typeorm';
export // Real repositories and relations for the lifecycle boundary; peripheral domain tables are omitted.
const schemas = [
  new EntitySchema<Resource>({
    name: 'Resource',
    target: Resource,
    tableName: 'resource',
    columns: {
      id: { type: Number, primary: true },
      name: { type: String },
      type: { type: String },
      allowTakeOver: { type: Boolean, default: true },
      supervisionMode: { type: String },
    },
  }),
  new EntitySchema<User>({
    name: 'User',
    target: User,
    tableName: 'user',
    columns: {
      id: { type: Number, primary: true },
      username: { type: String },
      creditBalance: { type: Number, default: 100 },
      billingFactor: { type: Number, default: 100 },
    },
  }),
  new EntitySchema<Project>({
    name: 'Project',
    target: Project,
    tableName: 'project',
    columns: {
      id: { type: Number, primary: true },
    },
  }),
  new EntitySchema<ResourceUsage>({
    name: 'ResourceUsage',
    target: ResourceUsage,
    tableName: 'resource_usage',
    columns: {
      id: { type: Number, primary: true, generated: true },
      resourceId: { type: Number },
      userId: { type: Number },
      usageAction: { type: String, default: ResourceUsageAction.Usage },
      startTime: { type: 'datetime' },
      startNotes: { type: String, nullable: true },
      endTime: { type: 'datetime', nullable: true },
      endNotes: { type: String, nullable: true },
      isFinalized: { type: Boolean, default: false },
      lifecyclePending: { type: Boolean, default: false },
      supervisorUserId: { type: Number, nullable: true },
      projectId: { type: Number, nullable: true },
      sessionDurationCreditsPerMinute: { type: Number, nullable: true },
      operatingDurationCreditsPerMinute: { type: Number, nullable: true },
      creditsPerUsage: { type: Number, nullable: true },
      billingFactor: { type: Number, nullable: true },
      attributedOperatingDurationInMinutes: { type: Number, nullable: true },
    },
    relations: {
      resource: { type: 'many-to-one', target: 'Resource', joinColumn: { name: 'resourceId' } },
      user: { type: 'many-to-one', target: 'User', joinColumn: { name: 'userId' } },
      supervisorUser: { type: 'many-to-one', target: 'User', joinColumn: { name: 'supervisorUserId' } },
      project: { type: 'many-to-one', target: 'Project', joinColumn: { name: 'projectId' } },
      billingTransaction: { type: 'one-to-one', target: 'BillingTransaction', inverseSide: 'resourceUsage' },
    },
  }),
  new EntitySchema<BillingTransaction>({
    name: 'BillingTransaction',
    target: BillingTransaction,
    tableName: 'billing_transaction',
    columns: {
      id: { type: Number, primary: true, generated: true },
      resourceUsageId: { type: Number },
      userId: { type: Number },
      amount: { type: Number },
      status: { type: String },
    },
    relations: {
      resourceUsage: { type: 'one-to-one', target: 'ResourceUsage', joinColumn: { name: 'resourceUsageId' } },
    },
  }),
  new EntitySchema<BillingTransactionItem>({
    name: 'BillingTransactionItem',
    target: BillingTransactionItem,
    tableName: 'billing_transaction_item',
    columns: {
      id: { type: Number, primary: true, generated: true },
      billingTransactionId: { type: Number },
      name: { type: String },
      description: { type: String, nullable: true },
      externalReference: { type: String, nullable: true },
      unitPrice: { type: Number },
      quantity: { type: Number },
    },
  }),
  new EntitySchema<FormSubmission>({
    name: 'FormSubmission',
    target: FormSubmission,
    tableName: 'form_submission',
    columns: {
      id: { type: Number, primary: true, generated: true },
      formId: { type: Number },
      resourceUsageId: { type: Number },
      userId: { type: Number },
      action: { type: String },
      data: { type: 'simple-json' },
    },
  }),
  new EntitySchema<ResourceUsageLifecycleAttempt>({
    name: 'ResourceUsageLifecycleAttempt',
    target: ResourceUsageLifecycleAttempt,
    tableName: 'resource_usage_lifecycle_attempt',
    columns: {
      id: { type: String, primary: true },
      resourceId: { type: Number },
      kind: { type: String },
      candidateUsageId: { type: Number, nullable: true },
      previousUsageId: { type: Number, nullable: true },
      transitionTime: { type: 'datetime' },
      formSubmissions: { type: 'simple-json' },
      billingItems: { type: 'simple-json' },
      createdAt: { type: 'datetime', createDate: true },
    },
    indices: [{ columns: ['resourceId'], unique: true }],
  }),
  new EntitySchema<ResourceOperatingInterval>({
    name: 'ResourceOperatingInterval',
    target: ResourceOperatingInterval,
    tableName: 'resource_operating_interval',
    columns: {
      id: { type: Number, primary: true, generated: true },
      resourceId: { type: Number },
      startTime: { type: 'datetime' },
      endTime: { type: 'datetime', nullable: true },
      startFlowNodeId: { type: String, nullable: true },
      startFlowRunId: { type: String, nullable: true },
      endFlowNodeId: { type: String, nullable: true },
      endFlowRunId: { type: String, nullable: true },
    },
  }),
];
