import {
  DrawerBackdrop,
  DrawerContent,
  DrawerDialog,
  type DrawerBackdropProps,
  type DrawerContentProps,
  type DrawerDialogProps,
} from '@heroui/react';

interface Props {
  isOpen: boolean;
  onOpenChange: (open: boolean) => void;
  children: DrawerDialogProps['children'];
  backdropProps?: Omit<DrawerBackdropProps, 'children' | 'isOpen' | 'onOpenChange'>;
  contentProps?: Omit<DrawerContentProps, 'children'>;
  dialogProps?: Omit<DrawerDialogProps, 'children'>;
}

// See StandardModal for why this is an inline style rather than a Tailwind
// class: each plugin bundles its own prefixed CSS, so a literal class here
// would only be generated by whichever plugin's build happens to scan this
// file. `--overlay` is a plain global CSS custom property, unaffected by
// per-plugin Tailwind prefixing.
const DEFAULT_DIALOG_STYLE = { backgroundColor: 'var(--overlay)' };

/**
 * Single source of truth for drawer chrome, shared by the host app and
 * plugins — see StandardModal. Wraps HeroUI's Drawer primitives with the
 * shared overlay token for contrast.
 */
export function StandardDrawer(props: Props) {
  const { isOpen, onOpenChange, children, backdropProps, contentProps, dialogProps } = props;

  const mergedDialogStyle = { ...DEFAULT_DIALOG_STYLE, ...dialogProps?.style };

  return (
    <DrawerBackdrop {...backdropProps} isOpen={isOpen} onOpenChange={onOpenChange}>
      <DrawerContent {...contentProps}>
        <DrawerDialog {...dialogProps} style={mergedDialogStyle}>
          {children}
        </DrawerDialog>
      </DrawerContent>
    </DrawerBackdrop>
  );
}
