import { registerAttractapGatewayFixture } from './websocket.gateway.attractap-gateway.test-fixture';
import { registerShouldBeDefinedCases } from './websocket.gateway.attractap-gateway.disconnect-reader.behaviors.test-cases';
import { registerLvglOutputSanitizationCases } from './websocket.gateway.attractap-gateway.disconnect-reader.behaviors.test-cases';
import { registerHandleConnectionCases } from './websocket.gateway.attractap-gateway.disconnect-reader.behaviors.test-cases';
import { registerHandleDisconnectCases } from './websocket.gateway.attractap-gateway.disconnect-reader.behaviors.test-cases';
import { registerOnHeartbeatCases } from './websocket.gateway.attractap-gateway.disconnect-reader.behaviors.test-cases';
import { registerOnClientEventCases } from './websocket.gateway.attractap-gateway.disconnect-reader.behaviors.test-cases';
import { registerSendResourceListCases } from './websocket.gateway.attractap-gateway.disconnect-reader.behaviors.test-cases';
import { registerDisconnectReaderCases } from './websocket.gateway.attractap-gateway.disconnect-reader.behaviors.test-cases';
describe('AttractapGateway', () => {
  const fixture = registerAttractapGatewayFixture();
  registerShouldBeDefinedCases(fixture);
  registerLvglOutputSanitizationCases(fixture);
  registerHandleConnectionCases(fixture);
  registerHandleDisconnectCases(fixture);
  registerOnHeartbeatCases(fixture);
  registerOnClientEventCases(fixture);
  registerSendResourceListCases(fixture);
  registerDisconnectReaderCases(fixture);
});
