import { registerSsooidcstrategyClaimPathResolutionFixture } from './oidc.strategy.ssooidcstrategy-claim-path-resolution.test-fixture';
import { registerRejectsMissingSubjectOrEmailBeforeAccountCreationAndHandlesAnUnsuccessfulCases } from './oidc.strategy.ssooidcstrategy-claim-path-resolution.normalizes-sso-usernames-before-user-creation.behaviors.test-cases';
import { registerMapsRoleStringsArraysAndObjectValuedClaimsWhileIgnoringNonStringEntriesCases } from './oidc.strategy.ssooidcstrategy-claim-path-resolution.audits-successful-oidc-user-creation-and-the-committed-role-delta.behaviors.test-cases';
import { registerResolvesUsernameUsingConfiguredUsernameClaimPathsCases } from './oidc.strategy.ssooidcstrategy-claim-path-resolution.resolves-email-using-configured-email-claim-paths.behaviors.test-cases';
import { registerResolvesEmailUsingConfiguredEmailClaimPathsCases } from './oidc.strategy.ssooidcstrategy-claim-path-resolution.resolves-email-using-configured-email-claim-paths.behaviors.test-cases';
import { registerAuditsSuccessfulOidcUserCreationAndTheCommittedRoleDeltaCases } from './oidc.strategy.ssooidcstrategy-claim-path-resolution.audits-successful-oidc-user-creation-and-the-committed-role-delta.behaviors.test-cases';
import { registerRecordsACreatedUserEvenWhenALaterRoleSyncFailsCases } from './oidc.strategy.ssooidcstrategy-claim-path-resolution.normalizes-sso-usernames-before-user-creation.behaviors.test-cases';
import { registerRecordsANewlyCreatedUserBeforeBindingFailureWithoutSilentlyDeletingItCases } from './oidc.strategy.ssooidcstrategy-claim-path-resolution.normalizes-sso-usernames-before-user-creation.behaviors.test-cases';
import { registerNormalizesSsoUsernamesBeforeUserCreationCases } from './oidc.strategy.ssooidcstrategy-claim-path-resolution.normalizes-sso-usernames-before-user-creation.behaviors.test-cases';
import { registerSyncsWithZeroAssignmentsWhenNoRoleMappingsConfiguredNoOpForFreshProviderCases } from './oidc.strategy.ssooidcstrategy-claim-path-resolution.syncs-with-zero-assignments-when-no-role-mappings-configured-no-op-for-fresh-provider.test-cases';
import { registerRevokesPreviouslyGrantedSsoRolesAfterTheMappingHasBeenClearedCases } from './oidc.strategy.ssooidcstrategy-claim-path-resolution.resolves-email-using-configured-email-claim-paths.behaviors.test-cases';
import { registerHonorsConfiguredPermissionMappingsAndRevokesAbsentRolesCases } from './oidc.strategy.ssooidcstrategy-claim-path-resolution.audits-successful-oidc-user-creation-and-the-committed-role-delta.behaviors.test-cases';
import { registerPassesTheExternalClaimValueThatGrantedEachRoleToTheSyncCases } from './oidc.strategy.ssooidcstrategy-claim-path-resolution.normalizes-sso-usernames-before-user-creation.behaviors.test-cases';
import { registerRevokesProviderRolesWhenTheTokenContainsAnExplicitlyEmptyRoleClaimCases } from './oidc.strategy.ssooidcstrategy-claim-path-resolution.resolves-email-using-configured-email-claim-paths.behaviors.test-cases';
import { registerDoesNotSyncWhenTheTokenContainsNoRoleGroupClaimsAtAllCases } from './oidc.strategy.ssooidcstrategy-claim-path-resolution.audits-successful-oidc-user-creation-and-the-committed-role-delta.behaviors.test-cases';
import { registerStrategyOptionsPassedToPassportOpenidconnectCases } from './oidc.strategy.ssooidcstrategy-claim-path-resolution.resolves-email-using-configured-email-claim-paths.behaviors.test-cases';
import { registerAuthenticatePerRequestCallbackUrlCases } from './oidc.strategy.ssooidcstrategy-claim-path-resolution.audits-successful-oidc-user-creation-and-the-committed-role-delta.behaviors.test-cases';
describe('SSOOIDCStrategy - claim path resolution', () => {
  const fixture = registerSsooidcstrategyClaimPathResolutionFixture();
  registerRejectsMissingSubjectOrEmailBeforeAccountCreationAndHandlesAnUnsuccessfulCases(fixture);
  registerMapsRoleStringsArraysAndObjectValuedClaimsWhileIgnoringNonStringEntriesCases(fixture);
  registerResolvesUsernameUsingConfiguredUsernameClaimPathsCases(fixture);
  registerResolvesEmailUsingConfiguredEmailClaimPathsCases(fixture);
  registerAuditsSuccessfulOidcUserCreationAndTheCommittedRoleDeltaCases(fixture);
  registerRecordsACreatedUserEvenWhenALaterRoleSyncFailsCases(fixture);
  registerRecordsANewlyCreatedUserBeforeBindingFailureWithoutSilentlyDeletingItCases(fixture);
  registerNormalizesSsoUsernamesBeforeUserCreationCases(fixture);
  registerSyncsWithZeroAssignmentsWhenNoRoleMappingsConfiguredNoOpForFreshProviderCases(fixture);
  registerRevokesPreviouslyGrantedSsoRolesAfterTheMappingHasBeenClearedCases(fixture);
  registerHonorsConfiguredPermissionMappingsAndRevokesAbsentRolesCases(fixture);
  registerPassesTheExternalClaimValueThatGrantedEachRoleToTheSyncCases(fixture);
  registerRevokesProviderRolesWhenTheTokenContainsAnExplicitlyEmptyRoleClaimCases(fixture);
  registerDoesNotSyncWhenTheTokenContainsNoRoleGroupClaimsAtAllCases(fixture);
  registerStrategyOptionsPassedToPassportOpenidconnectCases(fixture);
  registerAuthenticatePerRequestCallbackUrlCases(fixture);
});
