import { registerApiLogDestinationsOnInstalledNest11Fixture } from './routed-logger.api-log-destinations-on-installed-nest-11.test-fixture';
import { registerDefaultsToConsoleNormalizesDeduplicatesDestinationsAndIgnoresUnselectedFileCases } from './routed-logger.api-log-destinations-on-installed-nest-11.completes-shutdown-when-a-driver-finalizer-fails-synchronously-s.behaviors.test-cases';
import { registerRejectsUnknownNamesAndInvalidSelectedOptionsBeforeOpeningAnyTransportCases } from './routed-logger.api-log-destinations-on-installed-nest-11.keeps-console-formatting-and-stdout-stderr-routing-compatible-with-nest-and-fail2ban.behaviors.test-cases';
import { registerRetainsNestFilteringForLogLevelsJIncludingGapsAndFatalCallsCases } from './routed-logger.api-log-destinations-on-installed-nest-11.keeps-console-formatting-and-stdout-stderr-routing-compatible-with-nest-and-fail2ban.behaviors.test-cases';
import { registerRegistersAThirdTransportAndPreservesObjectVariadicMessagesContextAndSuppliCases } from './routed-logger.api-log-destinations-on-installed-nest-11.keeps-console-formatting-and-stdout-stderr-routing-compatible-with-nest-and-fail2ban.behaviors.test-cases';
import { registerKeepsConsoleFormattingAndStdoutStderrRoutingCompatibleWithNestAndFail2banCases } from './routed-logger.api-log-destinations-on-installed-nest-11.keeps-console-formatting-and-stdout-stderr-routing-compatible-with-nest-and-fail2ban.behaviors.test-cases';
import { registerDefaultsFileOutputToTheStorageRootSCases } from './routed-logger.api-log-destinations-on-installed-nest-11.completes-shutdown-when-a-driver-finalizer-fails-synchronously-s.behaviors.test-cases';
import { registerResolvesPathsCreatesDirectoriesFlushesUtf8AndAppendsOnRestartAbsoluteSCases } from './routed-logger.api-log-destinations-on-installed-nest-11.keeps-console-formatting-and-stdout-stderr-routing-compatible-with-nest-and-fail2ban.behaviors.test-cases';
import { registerFansOutOnceToConsoleAndFileCases } from './routed-logger.api-log-destinations-on-installed-nest-11.completes-shutdown-when-a-driver-finalizer-fails-synchronously-s.behaviors.test-cases';
import { registerIsolatesFileInitializationFailuresAndReportsOnceWithoutDisablingHealthyDrivCases } from './routed-logger.api-log-destinations-on-installed-nest-11.completes-shutdown-when-a-driver-finalizer-fails-synchronously-s.behaviors.test-cases';
import { registerIsolatesAsynchronousFileOpenErrorsEvenWhenShutdownBeginsBeforeOpeningComplCases } from './routed-logger.api-log-destinations-on-installed-nest-11.completes-shutdown-when-a-driver-finalizer-fails-synchronously-s.behaviors.test-cases';
import { registerIsolatesRuntimeDestinationFailuresSSuppressesSpamAndClosesHealthyDriversCases } from './routed-logger.api-log-destinations-on-installed-nest-11.completes-shutdown-when-a-driver-finalizer-fails-synchronously-s.behaviors.test-cases';
import { registerDoesNotBufferIndefinitelyOrThrowWhenAllDestinationsFailCases } from './routed-logger.api-log-destinations-on-installed-nest-11.completes-shutdown-when-a-driver-finalizer-fails-synchronously-s.behaviors.test-cases';
import { registerCompletesShutdownWhenADriverFinalizerFailsSynchronouslySCases } from './routed-logger.api-log-destinations-on-installed-nest-11.completes-shutdown-when-a-driver-finalizer-fails-synchronously-s.behaviors.test-cases';
import { registerForwardsAFileWriteStreamRuntimeErrorAndContinuesHealthyDeliveryWithoutRepCases } from './routed-logger.api-log-destinations-on-installed-nest-11.completes-shutdown-when-a-driver-finalizer-fails-synchronously-s.behaviors.test-cases';
import { registerReplaysBufferedBootstrapFrameworkLogsOnceAndKeepsTransportsOpenAcrossTempoCases } from './routed-logger.api-log-destinations-on-installed-nest-11.keeps-console-formatting-and-stdout-stderr-routing-compatible-with-nest-and-fail2ban.behaviors.test-cases';
describe('API log destinations on installed Nest 11', () => {
  const fixture = registerApiLogDestinationsOnInstalledNest11Fixture();
  registerDefaultsToConsoleNormalizesDeduplicatesDestinationsAndIgnoresUnselectedFileCases(fixture);
  registerRejectsUnknownNamesAndInvalidSelectedOptionsBeforeOpeningAnyTransportCases(fixture);
  registerRetainsNestFilteringForLogLevelsJIncludingGapsAndFatalCallsCases(fixture);
  registerRegistersAThirdTransportAndPreservesObjectVariadicMessagesContextAndSuppliCases(fixture);
  registerKeepsConsoleFormattingAndStdoutStderrRoutingCompatibleWithNestAndFail2banCases(fixture);
  registerDefaultsFileOutputToTheStorageRootSCases(fixture);
  registerResolvesPathsCreatesDirectoriesFlushesUtf8AndAppendsOnRestartAbsoluteSCases(fixture);
  registerFansOutOnceToConsoleAndFileCases(fixture);
  registerIsolatesFileInitializationFailuresAndReportsOnceWithoutDisablingHealthyDrivCases(fixture);
  registerIsolatesAsynchronousFileOpenErrorsEvenWhenShutdownBeginsBeforeOpeningComplCases(fixture);
  registerIsolatesRuntimeDestinationFailuresSSuppressesSpamAndClosesHealthyDriversCases(fixture);
  registerDoesNotBufferIndefinitelyOrThrowWhenAllDestinationsFailCases(fixture);
  registerCompletesShutdownWhenADriverFinalizerFailsSynchronouslySCases(fixture);
  registerForwardsAFileWriteStreamRuntimeErrorAndContinuesHealthyDeliveryWithoutRepCases(fixture);
  registerReplaysBufferedBootstrapFrameworkLogsOnceAndKeepsTransportsOpenAcrossTempoCases(fixture);
});
