import { registerMqttClientServiceFixture } from './mqtt-client.service.mqtt-client-service.test-fixture';
import { registerShouldBeDefinedCases } from './mqtt-client.service.mqtt-client-service.should-be-defined.test-cases';
import { registerUpdatesTheHealthyServerMetricAfterRegisteringAConnectedClientCases } from './mqtt-client.service.mqtt-client-service.updates-the-healthy-server-metric-after-registering-a-connected-client.test-cases';
import { registerTlsOptionsCases } from './mqtt-client.service.mqtt-client-service.tls-options.test-cases';
import { registerPublishCases } from './mqtt-client.service.mqtt-client-service.publish.test-cases';
import { registerSubscribeCases } from './mqtt-client.service.mqtt-client-service.subscribe.test-cases';
import { registerRefreshConnectionCases } from './mqtt-client.service.mqtt-client-service.refresh-connection.test-cases';
import { registerOnModuleDestroyCases } from './mqtt-client.service.mqtt-client-service.on-module-destroy.test-cases';
import { registerUnsubscribeCases } from './mqtt-client.service.mqtt-client-service.unsubscribe.test-cases';
describe('MqttClientService', () => {
  const fixture = registerMqttClientServiceFixture();
  registerShouldBeDefinedCases(fixture);
  registerUpdatesTheHealthyServerMetricAfterRegisteringAConnectedClientCases(fixture);
  registerTlsOptionsCases(fixture);
  registerPublishCases(fixture);
  registerSubscribeCases(fixture);
  registerRefreshConnectionCases(fixture);
  registerOnModuleDestroyCases(fixture);
  registerUnsubscribeCases(fixture);
});
