import { registerSsoAuditPolicyFixture } from './sso-audit.service.sso-audit-policy.test-fixture';
import { registerValidatesTheExactProvisioningChangeForSCases } from './sso-audit.service.sso-audit-policy.validates-the-exact-provisioning-change-for-s.test-cases';
import { registerBoundsTheTotalEncodedOidcSnapshotWhenIndividuallyValidFieldsExceedTheEnveCases } from './sso-audit.service.sso-audit-policy.bounds-the-total-encoded-oidc-snapshot-when-individually-valid-fields-exceed-the-enve.behaviors.test-cases';
import { registerProjectsASafeProviderLifecycleSnapshotCases } from './sso-audit.service.sso-audit-policy.bounds-the-total-encoded-oidc-snapshot-when-individually-valid-fields-exceed-the-enve.behaviors.test-cases';
import { registerCapturesSecurityMaterialPresenceWithoutRetainingItsValuesCases } from './sso-audit.service.sso-audit-policy.bounds-the-total-encoded-oidc-snapshot-when-individually-valid-fields-exceed-the-enve.behaviors.test-cases';
import { registerNormalizesAnEmptyOptionalSamlAudienceSoItsAuditEventIsRetainedCases } from './sso-audit.service.sso-audit-policy.bounds-the-total-encoded-oidc-snapshot-when-individually-valid-fields-exceed-the-enve.behaviors.test-cases';
import { registerStripsEndpointCredentialsQueriesAndFragmentsWhileRetainingABoundedMappingSCases } from './sso-audit.service.sso-audit-policy.rejects-secrets-malformed-deltas-and-provider-origin-attribution.behaviors.test-cases';
import { registerRetainsValidLargeSamlConfigurationsWithOpaqueEntityIdsAndOmissionMetadataCases } from './sso-audit.service.sso-audit-policy.rejects-secrets-malformed-deltas-and-provider-origin-attribution.behaviors.test-cases';
import { registerRejectsAuditSnapshotsContainingUnsafeEndpointUrlComponentsCases } from './sso-audit.service.sso-audit-policy.bounds-the-total-encoded-oidc-snapshot-when-individually-valid-fields-exceed-the-enve.behaviors.test-cases';
import { registerRetainsFullLifecycleEventsWithAnEscapedMaximumLengthNameJCases } from './sso-audit.service.sso-audit-policy.rejects-secrets-malformed-deltas-and-provider-origin-attribution.behaviors.test-cases';
import { registerStripsUrlCredentialsFromSamlEntityIdentifiersWhilePreservingUrnsCases } from './sso-audit.service.sso-audit-policy.rejects-secrets-malformed-deltas-and-provider-origin-attribution.behaviors.test-cases';
import { registerDoesNotLetOmissionMetadataAuthorizeRetainedSecretsOrArbitraryFieldNamesCases } from './sso-audit.service.sso-audit-policy.bounds-the-total-encoded-oidc-snapshot-when-individually-valid-fields-exceed-the-enve.behaviors.test-cases';
import { registerProjectsProviderOriginRoleSynchronizationWithoutAUserActorCases } from './sso-audit.service.sso-audit-policy.bounds-the-total-encoded-oidc-snapshot-when-individually-valid-fields-exceed-the-enve.behaviors.test-cases';
import { registerRejectsSecretsMalformedDeltasAndProviderOriginAttributionCases } from './sso-audit.service.sso-audit-policy.rejects-secrets-malformed-deltas-and-provider-origin-attribution.behaviors.test-cases';
describe('SSO audit policy', () => {
  const fixture = registerSsoAuditPolicyFixture();
  registerValidatesTheExactProvisioningChangeForSCases(fixture);
  registerBoundsTheTotalEncodedOidcSnapshotWhenIndividuallyValidFieldsExceedTheEnveCases(fixture);
  registerProjectsASafeProviderLifecycleSnapshotCases(fixture);
  registerCapturesSecurityMaterialPresenceWithoutRetainingItsValuesCases(fixture);
  registerNormalizesAnEmptyOptionalSamlAudienceSoItsAuditEventIsRetainedCases(fixture);
  registerStripsEndpointCredentialsQueriesAndFragmentsWhileRetainingABoundedMappingSCases(fixture);
  registerRetainsValidLargeSamlConfigurationsWithOpaqueEntityIdsAndOmissionMetadataCases(fixture);
  registerRejectsAuditSnapshotsContainingUnsafeEndpointUrlComponentsCases(fixture);
  registerRetainsFullLifecycleEventsWithAnEscapedMaximumLengthNameJCases(fixture);
  registerStripsUrlCredentialsFromSamlEntityIdentifiersWhilePreservingUrnsCases(fixture);
  registerDoesNotLetOmissionMetadataAuthorizeRetainedSecretsOrArbitraryFieldNamesCases(fixture);
  registerProjectsProviderOriginRoleSynchronizationWithoutAUserActorCases(fixture);
  registerRejectsSecretsMalformedDeltasAndProviderOriginAttributionCases(fixture);
});
