import { registerSsoServiceFixture } from './sso.service.sso-service.test-fixture';
import { registerShouldBeDefinedCases } from './sso.service.sso-service.create-provider.behaviors.test-cases';
import { registerGetAllProvidersCases } from './sso.service.sso-service.create-provider.behaviors.test-cases';
import { registerGetProviderByTypeAndIdCases } from './sso.service.sso-service.create-provider.behaviors.test-cases';
import { registerGetProviderByIdCases } from './sso.service.sso-service.create-provider.behaviors.test-cases';
import { registerCreateProviderCases } from './sso.service.sso-service.create-provider.behaviors.test-cases';
import { registerUpdateProviderCases } from './sso.service.sso-service.update-provider.test-cases';
import { registerUpdateOidcconfigurationClientSecretHandlingCases } from './sso.service.sso-service.create-provider.behaviors.test-cases';
import { registerUpdateOidcconfigurationRoleMappingsHandlingCases } from './sso.service.sso-service.create-provider.behaviors.test-cases';
import { registerDeleteProviderCases } from './sso.service.sso-service.create-provider.behaviors.test-cases';
import { registerSamlConfigurationHelpersCases } from './sso.service.sso-service.saml-configuration-helpers.test-cases';
describe('SsoService', () => {
  const fixture = registerSsoServiceFixture();
  registerShouldBeDefinedCases(fixture);
  registerGetAllProvidersCases(fixture);
  registerGetProviderByTypeAndIdCases(fixture);
  registerGetProviderByIdCases(fixture);
  registerCreateProviderCases(fixture);
  registerUpdateProviderCases(fixture);
  registerUpdateOidcconfigurationClientSecretHandlingCases(fixture);
  registerUpdateOidcconfigurationRoleMappingsHandlingCases(fixture);
  registerDeleteProviderCases(fixture);
  registerSamlConfigurationHelpersCases(fixture);
});
