import { registerSsoControllerFixture } from './sso.controller.sso-controller.test-fixture';
import { registerShouldBeDefinedCases } from './sso.controller.sso-controller.builds-and-validates-s-discovery-requests.behaviors.test-cases';
import { registerGetProvidersCases } from './sso.controller.sso-controller.builds-and-validates-s-discovery-requests.behaviors.test-cases';
import { registerGetProviderByIdCases } from './sso.controller.sso-controller.builds-and-validates-s-discovery-requests.behaviors.test-cases';
import { registerCreateProviderCases } from './sso.controller.sso-controller.builds-and-validates-s-discovery-requests.behaviors.test-cases';
import { registerUpdateProviderCases } from './sso.controller.sso-controller.update-provider.test-cases';
import { registerDeleteProviderCases } from './sso.controller.sso-controller.builds-and-validates-s-discovery-requests.behaviors.test-cases';
import { registerLinkUserToExternalAccountCases } from './sso.controller.sso-controller.link-user-to-external-account.test-cases';
import { registerOidcLoginCallbackCases } from './sso.controller.sso-controller.oidc-login-callback.test-cases';
import { registerBuildsAndValidatesSDiscoveryRequestsCases } from './sso.controller.sso-controller.builds-and-validates-s-discovery-requests.behaviors.test-cases';
import { registerSsoProvisioningEndpointsCases } from './sso.controller.sso-controller.sso-provisioning-endpoints.test-cases';
describe('SsoController', () => {
  const fixture = registerSsoControllerFixture();
  registerShouldBeDefinedCases(fixture);
  registerGetProvidersCases(fixture);
  registerGetProviderByIdCases(fixture);
  registerCreateProviderCases(fixture);
  registerUpdateProviderCases(fixture);
  registerDeleteProviderCases(fixture);
  registerLinkUserToExternalAccountCases(fixture);
  registerOidcLoginCallbackCases(fixture);
  registerBuildsAndValidatesSDiscoveryRequestsCases(fixture);
  registerSsoProvisioningEndpointsCases(fixture);
});
