import { registerResourcesServiceFixture } from './resources.service.resources-service.test-fixture';
import { registerCreatesAResourceWithUploadedImageAndRecordsActorAttributionAfterPersistencCases } from './resources.service.resources-service.creates-a-resource-with-uploaded-image-and-records-actor-attribution-after-persistenc.behaviors.test-cases';
import { registerRemovesTheNewResourceIfPersistingItsImageFilenameFailsCases } from './resources.service.resources-service.creates-a-resource-with-uploaded-image-and-records-actor-attribution-after-persistenc.behaviors.test-cases';
import { registerShouldBeDefinedCases } from './resources.service.resources-service.creates-a-resource-with-uploaded-image-and-records-actor-attribution-after-persistenc.behaviors.test-cases';
import { registerListResourcesCases } from './resources.service.listresources.permission-filtering.behaviors.test-cases';
import { registerGetResourceByIdCases } from './resources.service.resources-service.creates-a-resource-with-uploaded-image-and-records-actor-attribution-after-persistenc.behaviors.test-cases';
import { registerCreateResourceCases } from './resources.service.resources-service.create-resource.test-cases';
import { registerUpdateResourceCases } from './resources.service.resources-service.update-resource.test-cases';
import { registerDeleteResourceCases } from './resources.service.resources-service.creates-a-resource-with-uploaded-image-and-records-actor-attribution-after-persistenc.behaviors.test-cases';
describe('ResourcesService', () => {
  const fixture = registerResourcesServiceFixture();
  registerCreatesAResourceWithUploadedImageAndRecordsActorAttributionAfterPersistencCases(fixture);
  registerRemovesTheNewResourceIfPersistingItsImageFilenameFailsCases(fixture);
  registerShouldBeDefinedCases(fixture);
  registerListResourcesCases(fixture);
  registerGetResourceByIdCases(fixture);
  registerCreateResourceCases(fixture);
  registerUpdateResourceCases(fixture);
  registerDeleteResourceCases(fixture);
});
