import { registerSsoSamlStrategyValidateIntegrationE2eFixture } from './sso-saml.e2e.sso-saml-strategy-validate-integration-e2e.test-fixture';
import { registerCreatesANewUserOnFirstSamlAssertionCases } from './sso-saml.e2e.sso-saml-strategy-validate-integration-e2e.creates-a-new-user-on-first-saml-assertion.behaviors.test-cases';
import { registerReturnsTheSameUserOnRepeatSamlAssertionsNameIdDeduplicationCases } from './sso-saml.e2e.sso-saml-strategy-validate-integration-e2e.creates-a-new-user-on-first-saml-assertion.behaviors.test-cases';
import { registerResolvesEmailFromStandardSamlAttributeEmailCases } from './sso-saml.e2e.sso-saml-strategy-validate-integration-e2e.creates-a-new-user-on-first-saml-assertion.behaviors.test-cases';
import { registerResolvesEmailFromACustomSamlAttributeKeyCases } from './sso-saml.e2e.sso-saml-strategy-validate-integration-e2e.creates-a-new-user-on-first-saml-assertion.behaviors.test-cases';
import { registerResolvesDisplayNameFromStandardSamlAttributesCases } from './sso-saml.e2e.sso-saml-strategy-validate-integration-e2e.creates-a-new-user-on-first-saml-assertion.behaviors.test-cases';
import { registerSyncsSsoRolesWhenPermissionMappingsMatchTokenRolesCases } from './sso-saml.e2e.sso-saml-strategy-validate-integration-e2e.syncs-sso-roles-when-permission-mappings-match-token-roles.behaviors.test-cases';
import { registerRevokesSsoRolesWhenClaimsNoLongerIncludeThemCases } from './sso-saml.e2e.sso-saml-strategy-validate-integration-e2e.creates-a-new-user-on-first-saml-assertion.behaviors.test-cases';
import { registerThrowsWhenNameIdIsAbsentFromTheSamlProfileCases } from './sso-saml.e2e.sso-saml-strategy-validate-integration-e2e.syncs-sso-roles-when-permission-mappings-match-token-roles.behaviors.test-cases';
import { registerThrowsWhenEmailCannotBeResolvedFromTheSamlProfileCases } from './sso-saml.e2e.sso-saml-strategy-validate-integration-e2e.syncs-sso-roles-when-permission-mappings-match-token-roles.behaviors.test-cases';
describe('SSO SAML strategy — validate() integration (e2e)', () => {
  const fixture = registerSsoSamlStrategyValidateIntegrationE2eFixture();
  registerCreatesANewUserOnFirstSamlAssertionCases(fixture);
  registerReturnsTheSameUserOnRepeatSamlAssertionsNameIdDeduplicationCases(fixture);
  registerResolvesEmailFromStandardSamlAttributeEmailCases(fixture);
  registerResolvesEmailFromACustomSamlAttributeKeyCases(fixture);
  registerResolvesDisplayNameFromStandardSamlAttributesCases(fixture);
  registerSyncsSsoRolesWhenPermissionMappingsMatchTokenRolesCases(fixture);
  registerRevokesSsoRolesWhenClaimsNoLongerIncludeThemCases(fixture);
  registerThrowsWhenNameIdIsAbsentFromTheSamlProfileCases(fixture);
  registerThrowsWhenEmailCannotBeResolvedFromTheSamlProfileCases(fixture);
});
