import { registerMaintenanceServiceFixture } from './maintenance.service.maintenance-service.test-fixture';
import { registerCreatesScheduledMaintenanceWithDeferredNotificationsInATransactionCases } from './maintenance.service.maintenance-service.checks-active-maintenance-by-resource-or-schedule-through-the-supplied-transaction.behaviors.test-cases';
import { registerChecksActiveMaintenanceByResourceOrScheduleThroughTheSuppliedTransactionCases } from './maintenance.service.maintenance-service.checks-active-maintenance-by-resource-or-schedule-through-the-supplied-transaction.behaviors.test-cases';
import { registerShouldBeDefinedCases } from './maintenance.service.maintenance-service.maintenance-listing.behaviors.test-cases';
import { registerMaintenanceListingCases } from './maintenance.service.maintenance-service.maintenance-listing.behaviors.test-cases';
import { registerIndividualMaintenanceAccessCases } from './maintenance.service.maintenance-service.checks-active-maintenance-by-resource-or-schedule-through-the-supplied-transaction.behaviors.test-cases';
import { registerCreateMaintenanceCases } from './maintenance.service.maintenance-service.checks-active-maintenance-by-resource-or-schedule-through-the-supplied-transaction.behaviors.test-cases';
import { registerFinishMaintenanceCases } from './maintenance.service.maintenance-service.checks-active-maintenance-by-resource-or-schedule-through-the-supplied-transaction.behaviors.test-cases';
import { registerGetMaintenanceManagedResourceIdsCases } from './maintenance.service.maintenance-service.checks-active-maintenance-by-resource-or-schedule-through-the-supplied-transaction.behaviors.test-cases';
describe('MaintenanceService', () => {
  const fixture = registerMaintenanceServiceFixture();
  registerCreatesScheduledMaintenanceWithDeferredNotificationsInATransactionCases(fixture);
  registerChecksActiveMaintenanceByResourceOrScheduleThroughTheSuppliedTransactionCases(fixture);
  registerShouldBeDefinedCases(fixture);
  registerMaintenanceListingCases(fixture);
  registerIndividualMaintenanceAccessCases(fixture);
  registerCreateMaintenanceCases(fixture);
  registerFinishMaintenanceCases(fixture);
  registerGetMaintenanceManagedResourceIdsCases(fixture);
});
