apiVersion: 1

contactPoints:
  - orgId: 1
    name: attraccess-default
    receivers:
      - uid: attraccess-default-email
        type: email
        disableResolveMessage: false
        settings:
          addresses: alerts@example.invalid
          singleEmail: false
