#pragma once

#define TASK_PRIORITY_CLI 1
#define TASK_PRIORITY_LED 1
#define TASK_PRIORITY_API 1
#define TASK_PRIORITY_WIFI 1
#define TASK_PRIORITY_ETHERNET 1
#define TASK_PRIORITY_WEBSOCKET 1
#define TASK_PRIORITY_NFC 1
#define TASK_PRIORITY_DISPLAY_TOUCHSCREEN 1
#define TASK_PRIORITY_DISPLAY_OLED 1