import { registerSsosamlStrategyFixture } from './saml.strategy.ssosaml-strategy.test-fixture';
import { registerResolvesSamlEmailShapesWithoutLosingCustomAttributePrecedenceJCases } from './saml.strategy.ssosaml-strategy.records-a-created-user-even-when-a-later-role-sync-fails.behaviors.test-cases';
import { registerRejectsAssertionsWithoutAnyUsableEmailBeforeLookingUpAnAccountCases } from './saml.strategy.ssosaml-strategy.records-a-created-user-even-when-a-later-role-sync-fails.behaviors.test-cases';
import { registerBuildsPerRequestPassportSigningConfigurationWhenEncryptionIsSCases } from './saml.strategy.ssosaml-strategy.audits-successful-saml-user-creation-and-the-committed-role-delta.behaviors.test-cases';
import { registerUsesPerRequestSamlConfigurationForParallelValidationsCases } from './saml.strategy.ssosaml-strategy.syncs-rbac-roles-from-azure-ad-uri-style-group-claims-and-member-of.behaviors.test-cases';
import { registerNormalizesSamlDisplayNamesForNewUsersCases } from './saml.strategy.ssosaml-strategy.audits-successful-saml-user-creation-and-the-committed-role-delta.behaviors.test-cases';
import { registerAuditsSuccessfulSamlUserCreationAndTheCommittedRoleDeltaCases } from './saml.strategy.ssosaml-strategy.audits-successful-saml-user-creation-and-the-committed-role-delta.behaviors.test-cases';
import { registerRecordsACreatedUserEvenWhenALaterRoleSyncFailsCases } from './saml.strategy.ssosaml-strategy.records-a-created-user-even-when-a-later-role-sync-fails.behaviors.test-cases';
import { registerDoesNotSyncRolesWhenProfileHasNoRoleGroupAttributesOnlyEmailNameEtcCases } from './saml.strategy.ssosaml-strategy.audits-successful-saml-user-creation-and-the-committed-role-delta.behaviors.test-cases';
import { registerSyncsRbacRolesFromAzureAdUriStyleGroupClaimsAndMemberOfCases } from './saml.strategy.ssosaml-strategy.syncs-rbac-roles-from-azure-ad-uri-style-group-claims-and-member-of.behaviors.test-cases';
import { registerSyncsRbacRolesFromSamlRoleAttributesCases } from './saml.strategy.ssosaml-strategy.syncs-rbac-roles-from-azure-ad-uri-style-group-claims-and-member-of.behaviors.test-cases';
import { registerRevokesProviderRolesWhenARoleAttributeIsPresentButEmptyCases } from './saml.strategy.ssosaml-strategy.records-a-created-user-even-when-a-later-role-sync-fails.behaviors.test-cases';
import { registerRevokesPreviouslyGrantedSsoRolesAfterTheMappingHasBeenClearedCases } from './saml.strategy.ssosaml-strategy.records-a-created-user-even-when-a-later-role-sync-fails.behaviors.test-cases';
describe('SSOSamlStrategy', () => {
  const fixture = registerSsosamlStrategyFixture();
  registerResolvesSamlEmailShapesWithoutLosingCustomAttributePrecedenceJCases(fixture);
  registerRejectsAssertionsWithoutAnyUsableEmailBeforeLookingUpAnAccountCases(fixture);
  registerBuildsPerRequestPassportSigningConfigurationWhenEncryptionIsSCases(fixture);
  registerUsesPerRequestSamlConfigurationForParallelValidationsCases(fixture);
  registerNormalizesSamlDisplayNamesForNewUsersCases(fixture);
  registerAuditsSuccessfulSamlUserCreationAndTheCommittedRoleDeltaCases(fixture);
  registerRecordsACreatedUserEvenWhenALaterRoleSyncFailsCases(fixture);
  registerDoesNotSyncRolesWhenProfileHasNoRoleGroupAttributesOnlyEmailNameEtcCases(fixture);
  registerSyncsRbacRolesFromAzureAdUriStyleGroupClaimsAndMemberOfCases(fixture);
  registerSyncsRbacRolesFromSamlRoleAttributesCases(fixture);
  registerRevokesProviderRolesWhenARoleAttributeIsPresentButEmptyCases(fixture);
  registerRevokesPreviouslyGrantedSsoRolesAfterTheMappingHasBeenClearedCases(fixture);
});
