name: DependencyTrack SBOM

on:
  push:
    branches: [main]
  release:
    types: [published]

permissions:
  contents: read

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Upload SBOM to DependencyTrack
        uses: Quobis/action-owasp-dependecy-track-check@main
        with:
          url: ${{ vars.DEPENDENCYTRACK_API_URL }}
          key: ${{ secrets.DEPENDENCYTRACK_API_KEY }}
          language: nodejs
