name: Fabreader Firmware Build & Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'apps/fabreader-firmware/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}/firmware
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO and tools
        run: |
          python -m pip install --upgrade pip
          pip install platformio esptool
          pio upgrade

      - name: Build firmware
        id: build
        working-directory: apps/fabreader-firmware
        run: |
          echo "Building firmware..."
          pio run -e fabreader

          # Check if build was successful
          if [ -f ".pio/build/fabreader/firmware.bin" ]; then
            echo "build_success=true" >> $GITHUB_OUTPUT
          else
            echo "Build failed to produce firmware.bin"
            echo "build_success=false" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Create merged firmware
        working-directory: apps/fabreader-firmware
        run: |
          echo "Creating merged firmware for ESP Web Tools..."
          esptool.py --chip esp32c3 merge_bin \
            -o .pio/build/fabreader/merged-firmware.bin \
            --flash_mode dio \
            --flash_freq 40m \
            --flash_size 4MB \
            0x0 .pio/build/fabreader/bootloader.bin \
            0x8000 .pio/build/fabreader/partitions.bin \
            0x10000 .pio/build/fabreader/firmware.bin

      - name: Create manifest file
        working-directory: apps/fabreader-firmware
        run: |
          echo "Creating manifest file..."
          # Extract version from a file or set a default
          VERSION=$(date +"%Y.%m.%d")

          # Get the repository name from GitHub context
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          OWNER_NAME="${GITHUB_REPOSITORY%/*}"

          # Construct the firmware URL based on GitHub Pages - now in /firmware subdirectory
          FIRMWARE_URL="https://${OWNER_NAME}.github.io/${REPO_NAME}/firmware/merged-firmware.bin"

          cat > .pio/build/fabreader/manifest.json << EOF
          {
            "name": "Fabreader Firmware",
            "version": "$VERSION",
            "new_install_prompt_erase": true,
            "builds": [
              {
                "chipFamily": "ESP32-C3",
                "parts": [
                  { "path": "$FIRMWARE_URL", "offset": 0 }
                ]
              }
            ]
          }
          EOF

      - name: Download existing site if available
        run: |
          echo "Downloading existing site if available..."
          mkdir -p ./_site
          # Try to download the current site, but don't fail if it doesn't exist
          curl -s -o site.tar.gz "https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY#*/}/site.tar.gz" || true
          if [ -f "site.tar.gz" ]; then
            tar -xzf site.tar.gz -C ./_site
          fi

      - name: Prepare site for deployment
        run: |
          echo "Preparing site for deployment..."
          # Create directory structure for firmware
          mkdir -p ./_site/firmware

          # Copy firmware files
          cp apps/fabreader-firmware/.pio/build/fabreader/merged-firmware.bin ./_site/firmware/
          cp apps/fabreader-firmware/.pio/build/fabreader/manifest.json ./_site/firmware/

          # Create _headers file with CORS configuration
          cat > ./_site/_headers << EOL
          /*
            Access-Control-Allow-Origin: *
            Access-Control-Allow-Methods: GET, OPTIONS
            Access-Control-Allow-Headers: Content-Type
          EOL

          # Create an index.html page for the firmware path
          cat > ./_site/firmware/index.html << EOL
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Fabreader Firmware</title>
            <script type="module" src="https://unpkg.com/esp-web-tools@10/dist/web/install-button.js?module"></script>
            <style>
              body { font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif; line-height: 1.5; padding: 2rem; max-width: 800px; margin: 0 auto; }
              h1 { color: #333; }
              .install-container { margin: 2rem 0; padding: 1.5rem; border: 1px solid #ddd; border-radius: 8px; background: #f9f9f9; }
              .version { font-size: 0.9rem; color: #666; margin-bottom: 1rem; }
              pre { background: #f5f5f5; padding: 1rem; border-radius: 4px; overflow-x: auto; }
              .error-message { color: #e53935; padding: 1rem; border: 1px solid #f8d7da; background-color: #fff5f5; border-radius: 4px; display: none; }
              .not-supported { display: none; }
              .card { box-shadow: 0 4px 8px rgba(0,0,0,0.1); border-radius: 8px; padding: 1.5rem; margin: 2rem 0; background: white; }
              .requirements { background-color: #f8f9fa; }
              .build-info { font-size: 0.8rem; color: #666; margin-top: 2rem; }
              .back-link { margin-bottom: 1rem; }
            </style>
          </head>
          <body>
            <div class="back-link"><a href="/">← Back to Documentation</a></div>
            
            <h1>Fabreader Firmware Installer</h1>
            <p>Use this page to install or update your Fabreader device firmware using ESP Web Tools.</p>
            
            <div class="card requirements">
              <h3>⚠️ Requirements</h3>
              <ul>
                <li>Chrome or Edge browser on desktop (Web Serial is not supported on mobile or Firefox)</li>
                <li>ESP32-C3 based Fabreader device</li>
                <li>USB connection to your computer</li>
              </ul>
            </div>
            
            <div class="error-message" id="error-message">
              <p><strong>Error:</strong> <span id="error-text"></span></p>
            </div>
            
            <div class="install-container">
              <div class="version">Latest version: <span id="firmware-version">Loading...</span></div>
              <esp-web-install-button manifest="./manifest.json"></esp-web-install-button>
              <p class="not-supported" id="browser-not-supported">Your browser doesn't support Web Serial. Please use Chrome or Edge browser.</p>
            </div>
            
            <div class="card">
              <h2>Installation Instructions</h2>
              <ol>
                <li>Connect your Fabreader device to your computer using a USB cable</li>
                <li>Click the "Install" button above</li>
                <li>Select your device from the list when prompted</li>
                <li>Wait for the installation to complete</li>
              </ol>
            </div>
            
            <div class="card">
              <h2>Manual Installation</h2>
              <p>If the web installer doesn't work, you can download the firmware file and flash it manually:</p>
              <ol>
                <li>Download the <a href="./merged-firmware.bin" download>firmware binary</a></li>
                <li>Install <a href="https://github.com/espressif/esptool" target="_blank">esptool</a></li>
                <li>Flash using: <code>esptool.py --chip esp32c3 --port [PORT] --baud 921600 write_flash 0x0 merged-firmware.bin</code></li>
              </ol>
            </div>
            
            <div class="build-info">
              <p>Build date: $(date)</p>
              <p>Repository: ${GITHUB_REPOSITORY}</p>
              <p>Commit: ${GITHUB_SHA}</p>
            </div>
            
            <script>
              // Check if browser supports Web Serial
              if (!('serial' in navigator)) {
                document.getElementById('browser-not-supported').style.display = 'block';
              }
              
              // Fetch the manifest to display the current version
              fetch('./manifest.json')
                .then(response => {
                  if (!response.ok) {
                    throw new Error('Could not load firmware manifest. Status: ' + response.status);
                  }
                  return response.json();
                })
                .then(data => {
                  document.getElementById('firmware-version').textContent = data.version;
                })
                .catch(error => {
                  document.getElementById('firmware-version').textContent = 'Not available';
                  document.getElementById('error-message').style.display = 'block';
                  document.getElementById('error-text').textContent = error.message;
                  console.error('Error:', error);
                });
            </script>
          </body>
          </html>
          EOL

          # Create a tarball of the site for future workflows to reference
          tar -czf ./_site/site.tar.gz -C ./_site .

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
