name: Firmware Build

on:
  push:
    branches:
      - main
    paths:
      - 'apps/fabreader-firmware/**'
  pull_request:
    paths:
      - 'apps/fabreader-firmware/**'
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-firmware:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio
          pio upgrade

      - name: Install esptool
        run: pip install esptool

      - name: Build firmware
        working-directory: apps/fabreader-firmware
        run: pio run -e fabreader

      - name: Create merged firmware for ESP Web Tools
        working-directory: apps/fabreader-firmware
        run: |
          esptool.py --chip esp32c3 merge_bin \
            -o .pio/build/fabreader/merged-firmware.bin \
            --flash_mode dio \
            --flash_freq 40m \
            --flash_size 4MB \
            0x0 .pio/build/fabreader/bootloader.bin \
            0x8000 .pio/build/fabreader/partitions.bin \
            0xe000 .pio/build/fabreader/boot_app0.bin \
            0x10000 .pio/build/fabreader/firmware.bin

      - name: Create manifest file
        working-directory: apps/fabreader-firmware
        run: |
          # Extract version from a file or set a default
          VERSION=$(date +"%Y.%m.%d")

          # Get the repository name from GitHub context
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          OWNER_NAME="${GITHUB_REPOSITORY%/*}"

          # Construct the firmware URL based on GitHub Pages
          FIRMWARE_URL="https://${OWNER_NAME}.github.io/${REPO_NAME}/firmware/merged-firmware.bin"

          cat > .pio/build/fabreader/manifest.json << EOF
          {
            "name": "Fabreader Firmware",
            "version": "$VERSION",
            "new_install_prompt_erase": true,
            "builds": [
              {
                "chipFamily": "ESP32-C3",
                "parts": [
                  { "path": "$FIRMWARE_URL", "offset": 0 }
                ]
              }
            ]
          }
          EOF

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fabreader-firmware
          path: |
            apps/fabreader-firmware/.pio/build/fabreader/merged-firmware.bin
            apps/fabreader-firmware/.pio/build/fabreader/manifest.json

      - name: Upload firmware to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            apps/fabreader-firmware/.pio/build/fabreader/merged-firmware.bin
            apps/fabreader-firmware/.pio/build/fabreader/manifest.json
