name: Send Issue to OpenHands AI

on:
  issue_comment:
    types: [created]

jobs:
  send_to_openhands:
    if: github.event.comment.user.login == 'jappyjan' && contains(github.event.comment.body, '@ai')
    runs-on: ubuntu-latest
    steps:
      - name: Send Issue to OpenHands
        env:
          OPENHANDS_API_TOKEN: ${{ secrets.OPENHANDS_API_TOKEN }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          REPO_URL: ${{ github.event.repository.html_url }}
          COMMENTER_LOGIN: ${{ github.event.comment.user.login }}
        run: |
          # Prepare the initial message
          INITIAL_USER_MSG=$(printf "GitHub Issue: %s\n\n%s\n\nLink to issue: %s\nTriggered by: %s" \
          "${ISSUE_TITLE}" \
          "${ISSUE_BODY}" \
          "${ISSUE_URL}" \
          "${COMMENTER_LOGIN}")

          # Construct the JSON payload
          JSON_PAYLOAD=$(printf '{
            "initial_user_msg": "%s",
            "repository": "%s",
            "git_provider": "github"
          }' \
          "${INITIAL_USER_MSG}" \
          "${{ github.event.repository.full_name }}")

          # Make the API call
          # Defaulting to production server: https://app.all-hands.dev
          # Change if you use a local or self-hosted OpenHands instance.
          curl -X POST https://app.all-hands.dev/api/conversations \
            -H "Authorization: Bearer ${OPENHANDS_API_TOKEN}" \
            -H "Content-Type: application/json" \
            -d "${JSON_PAYLOAD}"
